<?php

if ( ! class_exists( 'WPCFeedStatics' ) ) {

	class WPCFeedStatics {
		private static $instance; //singleton instance
		private $prefix = 'WPCFeedStatics';

		public static function get_instance() {
			if ( self::$instance === null ) {
				self::$instance = new self;
			}

			return self::$instance;
		}

		public function remove_dia( $text ) {
			$prevodniTabulka = array(
				'ä' => 'a',
				'Ä' => 'A',
				'á' => 'a',
				'Á' => 'A',
				'à' => 'a',
				'À' => 'A',
				'ã' => 'a',
				'Ã' => 'A',
				'â' => 'a',
				'Â' => 'A',
				'č' => 'c',
				'Č' => 'C',
				'ć' => 'c',
				'Ć' => 'C',
				'ď' => 'd',
				'Ď' => 'D',
				'ě' => 'e',
				'Ě' => 'E',
				'é' => 'e',
				'É' => 'E',
				'ë' => 'e',
				'Ë' => 'E',
				'è' => 'e',
				'È' => 'E',
				'ê' => 'e',
				'Ê' => 'E',
				'í' => 'i',
				'Í' => 'I',
				'ï' => 'i',
				'Ï' => 'I',
				'ì' => 'i',
				'Ì' => 'I',
				'î' => 'i',
				'Î' => 'I',
				'ľ' => 'l',
				'Ľ' => 'L',
				'ĺ' => 'l',
				'Ĺ' => 'L',
				'ń' => 'n',
				'Ń' => 'N',
				'ň' => 'n',
				'Ň' => 'N',
				'ñ' => 'n',
				'Ñ' => 'N',
				'ó' => 'o',
				'Ó' => 'O',
				'ö' => 'o',
				'Ö' => 'O',
				'ô' => 'o',
				'Ô' => 'O',
				'ò' => 'o',
				'Ò' => 'O',
				'õ' => 'o',
				'Õ' => 'O',
				'ő' => 'o',
				'Ő' => 'O',
				'ř' => 'r',
				'Ř' => 'R',
				'ŕ' => 'r',
				'Ŕ' => 'R',
				'š' => 's',
				'Š' => 'S',
				'ś' => 's',
				'Ś' => 'S',
				'ť' => 't',
				'Ť' => 'T',
				'ú' => 'u',
				'Ú' => 'U',
				'ů' => 'u',
				'Ů' => 'U',
				'ü' => 'u',
				'Ü' => 'U',
				'ù' => 'u',
				'Ù' => 'U',
				'ũ' => 'u',
				'Ũ' => 'U',
				'û' => 'u',
				'Û' => 'U',
				'ý' => 'y',
				'Ý' => 'Y',
				'ž' => 'z',
				'Ž' => 'Z',
				'ź' => 'z',
				'Ź' => 'Z'
			);

			$text = strtr( $text, $prevodniTabulka );

			return $text;
		}

		public function color_translate( $color ) {
			$color_replace = $this->remove_dia( str_replace( '-', ' ', $color ) );

			$translate = array(
				'zyan'                     => 'azurová',
				'zwart'                    => 'černá',
				'zolty'                    => 'žlutá',
				'zloty'                    => 'zlatá',
				'zitronengelb'             => 'citrónová',
				'zilver'                   => 'stříbrná',
				'zielony'                  => 'zelená',
				'zielonoszary'             => 'šedozelená',
				'zieleń morska'            => 'mořská zelená',
				'zeegroen'                 => 'mořská zelená',
				'zalmroze'                 => 'lososová',
				'wit'                      => 'bílá',
				'wiśniowy'                 => 'třešňově červená',
				'weiß'                     => 'bílá',
				'waldgrün'                 => 'lesní zelená',
				'turkusowy'                => 'tyrkysová',
				'turkoois'                 => 'tyrkysová',
				'türkis'                   => 'tyrkysová',
				'truskawkowy'              => 'jahodová',
				'taupe'                    => 'světle hnědá',
				'szmaragdowy'              => 'smaragdová',
				'szary'                    => 'šedá',
				'szałwiowy'                => 'šalvějová',
				'stalblau'                 => 'ocelová modrá',
				'staalblauw'               => 'ocelová modrá',
				'srebrny'                  => 'stříbrná',
				'smaragdgrün'              => 'smaragdová',
				'smaragdgroen'             => 'smaragdová',
				'silber'                   => 'stříbrná',
				'senfgelb'                 => 'hořčičná',
				'schwarz'                  => 'černá',
				'schokoladenbraun'         => 'čokoládově hnědá',
				'salie'                    => 'šalvějová',
				'salbei'                   => 'šalvějová',
				'rozowy'                   => 'růžová',
				'roze'                     => 'růžová',
				'rot'                      => 'červená',
				'rosa'                     => 'růžová',
				'rood'                     => 'červená',
				'pomaranczowy'             => 'oranžová',
				'pfirsich'                 => 'broskvová',
				'perzik'                   => 'broskvová',
				'paars'                    => 'fialová',
				'oranje'                   => 'oranžová',
				'orange'                   => 'oranžová',
				'oliwkowy'                 => 'olivová',
				'oliv'                     => 'olivová',
				'olijf'                    => 'olivová',
				'niebieski'                => 'modrá',
				'munt'                     => 'mentolová',
				'mosterdgeel'              => 'hořčičná',
				'mosiezny'                 => 'mechově zelená',
				'mosgroen'                 => 'mechově zelená',
				'morski'                   => 'námořnická modrá',
				'moosgrün'                 => 'mechově zelená',
				'minze'                    => 'mentolová',
				'miętowy'                  => 'mentolová',
				'miedziany'                => 'měděná',
				'meergrün'                 => 'mořská zelená',
				'marynistyczny'            => 'námořnická modrá',
				'marineblauw'              => 'námořnická modrá',
				'marineblau'               => 'námořnická modrá',
				'marine'                   => 'námořnická modrá',
				'magenta'                  => 'purpurová',
				'łososiowy'                => 'lososová',
				'lila'                     => 'lila',
				'leśny'                    => 'lesní zelená',
				'lawendowy'                => 'levandulová',
				'lavendel'                 => 'levandulová',
				'lachsrosa'                => 'lososová',
				'kupfer'                   => 'měděná',
				'kremowy'                  => 'světle hnědá',
				'kość słoniowa'            => 'slonovinová',
				'koralowy'                 => 'korálová',
				'koralle'                  => 'korálová',
				'koraal'                   => 'korálová',
				'koper'                    => 'měděná',
				'kirschrot'                => 'třešňově červená',
				'kersrood'                 => 'třešňově červená',
				'kasztanowy'               => 'kaštanová',
				'kastanjebruin'            => 'kaštanová',
				'kastanienbraun'           => 'kaštanová',
				'karminrot'                => 'karmínová',
				'karminowy'                => 'karmínová',
				'karmijnrood'              => 'karmínová',
				'karmazynowy'              => 'bordó',
				'kaki'                     => 'khaki',
				'ivoor'                    => 'slonovinová',
				'indygo'                   => 'indigová',
				'indigo'                   => 'indigová',
				'grün'                     => 'zelená',
				'groen'                    => 'zelená',
				'grijsgroen'               => 'šedozelená',
				'grijs'                    => 'šedá',
				'graugrün'                 => 'šedozelená',
				'grau'                     => 'šedá',
				'goud'                     => 'zlatá',
				'gorczycowy'               => 'hořčičná',
				'gold'                     => 'zlatá',
				'gelb'                     => 'žlutá',
				'geel'                     => 'žlutá',
				'fioletowy'                => 'fialová',
				'erdbeere'                 => 'jahodová',
				'elfenbein'                => 'slonovinová',
				'czerwony'                 => 'červená',
				'czekoladowy'              => 'čokoládově hnědá',
				'czarny'                   => 'černá',
				'cytrynowy'                => 'citrónová',
				'cyjan'                    => 'azurová',
				'cyaan'                    => 'azurová',
				'citroengeel'              => 'citrónová',
				'chocoladebruin'           => 'čokoládově hnědá',
				'chartreuse'               => 'chartreuská',
				'bursztynowy'              => 'jantarová',
				'brzoskwiniowy'            => 'broskvová',
				'bruin'                    => 'hnědá',
				'brązowy'                  => 'hnědá',
				'braun'                    => 'hnědá',
				'bosgroen'                 => 'lesní zelená',
				'bordeauxrot'              => 'bordó',
				'bordeaux'                 => 'bordó',
				'blauw'                    => 'modrá',
				'blau'                     => 'modrá',
				'blau staal'               => 'ocelová modrá',
				'bialy'                    => 'bílá',
				'bezowy'                   => 'béžová',
				'bernstein'                => 'jantarová',
				'beige'                    => 'béžová',
				'bakłażanowy'              => 'baklažánová',
				'aubergine'                => 'baklažánová',
				'aprykotowy'               => 'meruňková',
				'aprikose'                 => 'meruňková',
				'amber'                    => 'jantarová',
				'abrikoos'                 => 'meruňková',
				'aardbei'                  => 'jahodová',
				'zviratka'                 => 'zviratka',
				'zlute'                    => 'žlutá',
				'zluta'                    => 'žlutá',
				'zlta'                     => 'žlutá',
				'zlaty'                    => 'zlatá',
				'zlata'                    => 'zlatá',
				'zirafa'                   => 'žirafa',
				'zip hoodies'              => 'mikina na zip',
				'zimni cerna'              => 'zimní černá',
				'zicron stone black'       => 'zicron kámen černý',
				'zena'                     => 'žena',
				'zeleno zluta'             => 'zelená žlutá',
				'zelene'                   => 'zelená',
				'zelena'                   => 'zelená',
				'zebra'                    => 'zebra',
				'ze zipem'                 => 'se zipem',
				'zarive ruzova'            => 'zářivě růžová',
				'yw'                       => 'žlutá',
				'yollew'                   => 'žlutá',
				'yl'                       => 'žlutá',
				'yellowpearl'              => 'žlutá perla',
				'yellowmen'                => 'žlutá',
				'yellowish brown'          => 'žlutohnědá',
				'yellowgold'               => 'žluté zlato',
				'yellowflower'             => 'žlutý květ',
				'yellow'                   => 'žlutá',
				'yelllow'                  => 'žlutá',
				'yeellow and blue'         => 'žluté a modré',
				'ye'                       => 'žlutá',
				'wt'                       => 'bílá',
				'wood'                     => 'dřevo',
				'wolf'                     => 'vlk',
				'withe'                    => 'vrbový prut',
				'witch'                    => 'čarodějnice',
				'winter jasmine'           => 'zimní jasmín',
				'winred'                   => 'červená',
				'winnie'                   => 'medvídek',
				'wings of freedom'         => 'křídla svobody',
				'winesandals'              => 'vinné sandály',
				'winered'                  => 'červené víno',
				'wine red'                 => 'červené víno',
				'wind red'                 => 'vítr červený',
				'wig'                      => 'paruka',
				'whtie'                    => 'bílá',
				'whole black leather'      => 'celá černá kůže',
				'whlite'                   => 'bílá',
				'whitemen'                 => 'bílá',
				'whitei'                   => 'bílá',
				'whiteh'                   => 'bílá',
				'whitegray'                => 'bílošedá',
				'whitegold clear'          => 'bílé zlato čiré',
				'whitecotton'              => 'bílá bavlna',
				'whitec'                   => 'bílá',
				'whiteblue'                => 'bílomodrá',
				'whiteblack'               => 'bílo černá',
				'white'                    => 'bílá',
				'wheat blue'               => 'pšeničná modrá',
				'whale'                    => 'velryba',
				'wh'                       => 'bílá',
				'wert'                     => 'wert',
				'wave point'               => 'vlnový bod',
				'waterproof'               => 'voděodolný',
				'watermelon red'           => 'melounová červená',
				'waterdrop'                => 'kapka vody',
				'watercolor green'         => 'akvarel zelená',
				'water is blue'            => 'voda je modrá',
				'warm white'               => 'teplá bílá',
				'walnut'                   => 'vlašský ořech',
				'wall mounted'             => 'na stěnu',
				'vzor plody more'          => 'vzor plody moře',
				'vojenska zelena'          => 'vojenská zelená',
				'vlk'                      => 'vlk',
				'viz foto'                 => 'viz foto',
				'virgo'                    => 'panna',
				'violets'                  => 'fialová',
				'violet'                   => 'fialová',
				'vintage'                  => 'vintage',
				'vinove'                   => 'vínová',
				'vinova'                   => 'vínová',
				'vinona'                   => 'vinona',
				'vin rouge'                => 'vin rouge',
				'vicebarevna'              => 'vícebarevná',
				'vesmir'                   => 'vesmír',
				'vertical peony'           => 'vertikální pivoňka',
				'velvet brown'             => 'sametově hnědá',
				'velryby'                  => 'velryby',
				'velryba'                  => 'velryba',
				'velcro black'             => 'suchý zip černý',
				'vegetable'                => 'zelenina',
				'vegeta'                   => 'vegeta',
				'valentine girl boy'       => 'valentine dívka chlapec',
				'usmev'                    => 'úsměv',
				'usb warm white'           => 'usb teplá bílá',
				'unicorn'                  => 'jednorožec',
				'underwater world'         => 'podvodní svět',
				'ultra tenke'              => 'ultra tenke',
				'ufo'                      => 'ufo',
				'tyrtysova'                => 'tyrtysova',
				'tyrkysova'                => 'tyrkysová',
				'tygr'                     => 'tygr',
				'turtleneck wine red'      => 'rolák vínově červený',
				'turtle'                   => 'želva',
				'turquoise'                => 'tyrkysová',
				'turmeric'                 => 'kurkuma',
				'tulle'                    => 'tyl',
				'tucnak'                   => 'tučňák',
				'tshirt'                   => 'tričko',
				'ts'                       => 'ts',
				'tropical leaves'          => 'tropické listy',
				'tricko'                   => 'trik',
				'tricerotops'              => 'trierotops',
				'triangle'                 => 'trojúhelník',
				'trees'                    => 'stromy',
				'tree'                     => 'strom',
				'transparentni'            => 'transparentní',
				'transparent'              => 'průhledná / transparentní',
				'tractor'                  => 'traktor',
				'toys set'                 => 'sada hraček',
				'toydoll'                  => 'hračka',
				'tortoiseshell'            => 'želvovina',
				'tortoise'                 => 'želva',
				'top'                      => 'horní',
				'tomato'                   => 'rajče',
				'tnave modra'              => 'tmavě modrá',
				'tmavohneda'               => 'tmavohnědá',
				'tmave'                    => 'tmavé',
				'tmave modra'              => 'tmavě modrá',
				'tmava modra'              => 'tmavá modrá',
				'tigger'                   => 'tygr',
				'tiger'                    => 'tygr',
				'tiffany blue'             => 'tiffany modrá',
				'tie dye'                  => 'barva na kravatu',
				'tibetan green'            => 'tibetská zelená',
				'thunder'                  => 'hrom',
				'three pictures'           => 'tři obrázky',
				'thousand love'            => 'tisíc lásky',
				'thor'                     => 'thor',
				'thin matt'                => 'tenký matný',
				'thickened light'          => 'zahuštěné světlo',
				'thick black'              => 'tlustá černá',
				'the picture color'        => 'barva obrázku',
				'tepla bila'               => 'tepla bílá',
				'tender pink'              => 'něžná růžová',
				'telova'                   => 'tělová',
				'teambride light blue'     => 'teambride světle modrá',
				'teal'                     => 'modrozelená',
				'tea'                      => 'čaj',
				'taurus'                   => 'býk',
				'taro purple'              => 'taro fialová',
				'tankini set green'        => 'sada tankini zelená',
				'tan'                      => 'opálení',
				'symphony blue'            => 'symfonická modrá',
				'swimming ring a'          => 'plavecký kroužek a',
				'swhite'                   => 'bílá',
				'sweatshirt'               => 'mikina',
				'sweater khaki'            => 'khaki svetr',
				'swan'                     => 'labuť',
				'svitive zelena'           => 'živá zelená',
				'svetlehnede'              => 'světlehnědé',
				'svetlehneda'              => 'světlehnědá',
				'svetle'                   => 'světlý',
				'svetle modra'             => 'světle modrá',
				'svetla zelena'            => 'světla zelená',
				'surfing'                  => 'surfování',
				'superman'                 => 'superman',
				'superficial'              => 'povrchní',
				'super'                    => 'super',
				'sunset'                   => 'západ slunce',
				'sunscreen thin blue'      => 'opalovací krém tenký modrý',
				'sunny yellow'             => 'slunečně žlutá',
				'sunglasses'               => 'sluneční brýle',
				'sunflower'                => 'slunečnice',
				'sun flower'               => 'slunečnice',
				'summer beige'             => 'letní béžová',
				'sukne celenka'            => 'sukne celenka',
				'suit light blue'          => 'oblek světle modrý',
				'styled rose red'          => 've stylu růžově červené',
				'stylec khaki'             => 'stylec khaki',
				'styleb gray'              => 'styleb šedá',
				'stylea deep brown'        => 'stylea tmavě hnědá',
				'studena bila'             => 'studena bila',
				'strong dog leash'         => 'silné psí vodítko',
				'stripy girl'              => 'pruhovaná dívka',
				'stripes'                  => 'pruhy',
				'striped'                  => 'pruhová',
				'stripe'                   => 'proužek',
				'strip c'                  => 'proužek c',
				'stribrna'                 => 'stříbrná',
				'strawberry'               => 'jahoda',
				'stranger things'          => 'cizí věci',
				'straight pin'             => 'rovný čep',
				'stone'                    => 'kámen',
				'stegosaurus'              => 'stegosaurus',
				'steel black blue'         => 'ocelově černá modrá',
				'stars'                    => 'hvězdy',
				'starrysky'                => 'hvězdná obloha',
				'starry sky'               => 'hvězdná obloha',
				'starlight'                => 'světlo hvězd',
				'starfish'                 => 'mořská hvězdice',
				'star'                     => 'hvězda',
				'standing old man'         => 'stojící starý muž',
				'stainless steel'          => 'nerezová ocel',
				'sred'                     => 'sred',
				'squirtle'                 => 'veverka',
				'square'                   => 'náměstí',
				'spring green'             => 'jarní zelená',
				'sports black'             => 'sportovní černá',
				'sponge'                   => 'houba na mytí',
				'spike picture a'          => 'špice obrázek a',
				'spiderman'                => 'pavoučí muž',
				'spider'                   => 'pavouk',
				'spain'                    => 'španělsko',
				'solid black'              => 'černá',
				'solar blue light'         => 'solární modré světlo',
				'sob'                      => 'vzlyk',
				'snowman'                  => 'sněhulák',
				'snowflake'                => 'sněhová vločka',
				'snehurka'                 => 'sněhurka',
				'sneakers black red'       => 'tenisky černo červené',
				'snakeskin print'          => 'potisk hadí kůže',
				'smiley'                   => 'smajlík',
				'smetanova'                => 'smetanová',
				'small pink love'          => 'malá růžová láska',
				'slonova kost'             => 'slonova kost',
				'slonici'                  => 'slonici',
				'slon'                     => 'slon',
				'sliver'                   => 'střípek',
				'slippers blue'            => 'pantofle modré',
				'slipper gray'             => 'pantofle šedá',
				'sleep'                    => 'spát',
				'slate'                    => 'břidlice',
				'skype blue wood'          => 'skype modré dřevo',
				'skybluemen'               => 'skybluemen',
				'skyblue'                  => 'modrá obloha',
				'sky blue'                 => 'modrá obloha',
				'skublue'                  => 'skublue',
				'skirt'                    => 'sukně',
				'skin'                     => 'kůže',
				'skeleton'                 => 'kostra',
				'sipky'                    => 'sipky',
				'singlnet white green'     => 'singlenet bílá zelená',
				'singlenet white pink'     => 'singlenet bílá růžová',
				'singel panty'             => 'jednotné kalhotky',
				'silvery'                  => 'stříbrná',
				'silver'                   => 'stříbrná',
				'silne narazuvzdorne'      => 'silne narazuvzdorne',
				'shrimp'                   => 'krevety',
				'shown'                    => 'zobrazeno',
				'shoulder carrier b'       => 'ramenní nosič b',
				'shorts'                   => 'šortky',
				'short sleeve'             => 'krátký rukáv',
				'shiny green'              => 'lesklá zelená',
				'shiiny rose gold'         => 'lesklé růžové zlato',
				'sheep'                    => 'ovce',
				'shark'                    => 'žralok',
				'shallow lotus ash'        => 'mělký lotosový popel',
				'sgreen'                   => 'zelený',
				'sgray'                    => 'šedivý',
				'set'                      => 'set',
				'sequined khaki'           => 'khaki s flitry',
				'sequin black'             => 'flitr černý',
				'sent at random'           => 'odesláno náhodně',
				'sedy'                     => 'sedy',
				'sedo ruzove'              => 'sedo růžové',
				'sediva'                   => 'šedivá',
				'sede'                     => 'šedé',
				'sede alien hi'            => 'sede mimozemšťan ahoj',
				'seda'                     => 'šedá',
				'seda tmava'               => 'seda tmavá',
				'scyther'                  => 'kosa',
				'scrub blue'               => 'drhnout modře',
				'scorpio'                  => 'štír',
				'scarlet'                  => 'šarlatový',
				'scarf bear'               => 'šátek medvěd',
				'scarecrow'                => 'strašák',
				'sblue'                    => 'modrá',
				'sapphire'                 => 'safírová',
				'santa claus'              => 'santa claus',
				'sandy waterproof'         => 'písčitá voděodolná',
				'sandals white blue'       => 'sandály bílo modré',
				'sand'                     => 'písek',
				'samotna'                  => 'samotna',
				'sailorblue   white'       => 'námořník modrá bílá',
				'sailor blue   black'      => 'námořník modrá černá',
				'sailboatrainbow'          => 'plachetnice',
				'sagittarius'              => 'střelec',
				'safirova modra'           => 'safirova modra',
				'safflower'                => 'světlice barvířská',
				'sada'                     => 'sada',
				'sad'                      => 'smutný',
				'ryba'                     => 'ryba',
				'ruzovy'                   => 'růžová',
				'ruzovo fialova'           => 'růžovo fialová',
				'ruzove'                   => 'růžové',
				'ruzova'                   => 'růžová',
				'rutilated quartz sedy'    => 'rutilovaný křemen sedy',
				'rust red'                 => 'rezavě červená',
				'russia'                   => 'rusko',
				'russet'                   => 'červenohnědý',
				'ruins green'              => 'ruiny zelené',
				'ruffle sleeve set'        => 'sada volánových rukávů',
				'ruby red heart'           => 'rubínově červené srdce',
				'royel blue b'             => 'královská modř b',
				'royalblue'                => 'královská modrá',
				'royal blue'               => 'královská modrá',
				'round'                    => 'kolo',
				'rough vertical bar'       => 'hrubá svislá lišta',
				'rouge red'                => 'červená červená',
				'rosy red'                 => 'růžově červená',
				'rosered'                  => 'růže červená',
				'rosepink'                 => 'růžová růže',
				'roseleop'                 => 'roseleop',
				'rosegold'                 => 'rosegold',
				'roseblack'                => 'růžově černá',
				'rose red'                 => 'růže červená',
				'rope add crown'           => 'provaz přidat korunu',
				'rocket'                   => 'raketa',
				'rock cyan black'          => 'rock azurově černá',
				'robot'                    => 'robot',
				'robe lake blue'           => 'roucho jezerní modré',
				'right'                    => 'že jo',
				'rice white'               => 'rýže bílá',
				'ribbon black'             => 'stuha černá',
				'rhododendron'             => 'rododendron',
				'retro'                    => 'retro',
				'repair the moon'          => 'opravit měsíc',
				'remote and touch'         => 'dálkové a dotykové',
				'redwine'                  => 'červené víno',
				'reddish brown'            => 'červenohnědá',
				'redbrown black'           => 'červenohnědá černá',
				'redboots'                 => 'červené boty',
				'red'                      => 'červené',
				'recessed in'              => 'zapuštěný v',
				'rd'                       => 'červená',
				'rc changeable'            => 'rc měnitelný',
				'random color'             => 'náhodná barva',
				'raketa'                   => 'raketa',
				'rainbowpink'              => 'duhově růžová',
				'rainbowblue'              => 'duhově modrá',
				'rainbowblack'             => 'duhově černá',
				'rainbow'                  => 'duha',
				'rabbit'                   => 'králičí',
				'quicksand case women'     => 'ženy pouzdro z tekutého písku',
				'queen'                    => 'královna',
				'purplish red'             => 'purpurově červená',
				'purpleboots'              => 'fialové boty',
				'purple'                   => 'fialová',
				'pure black'               => 'čistě černá',
				'pup'                      => 'štěně',
				'puntiky'                  => 'puntiky',
				'pumpkin'                  => 'dýně',
				'pullover'                 => 'svetr',
				'puff sleeve bk'           => 'nafouknutý rukáv bk',
				'publue'                   => 'publue',
				'publack'                  => 'veřejnost',
				'pruple'                   => 'pruple',
				'pruhledny'                => 'pruhledny',
				'pruhledna'                => 'pruhledna',
				'prouzky'                  => 'prouzky',
				'printing'                 => 'tisk',
				'print'                    => 'tisk',
				'princessgirl'             => 'princezna',
				'princess pink'            => 'princezna růžová',
				'princeboy'                => 'princboy',
				'pride edition'            => 'edice hrdosti',
				'pricot'                   => 'meruňka',
				'prase'                    => 'prase',
				'prasatko'                 => 'prasátko',
				'pp'                       => 'fialová',
				'powdery purple'           => 'pudrově fialová',
				'powdered strawberry'      => 'prášková jahoda',
				'powder blue'              => 'modrý prášek',
				'positioning flower'       => 'polohovací květina',
				'popelka'                  => 'popelka',
				'polka dot'                => 'puntíkovaný',
				'police blue'              => 'policejní modrá',
				'polarized'                => 'polarizované',
				'pokemon hoodie'           => 'pokemon mikina s kapucí',
				'pocket with zipper'       => 'kapsa se zipem',
				'plush black'              => 'plyšová černá',
				'plus velvet black'        => 'plus sametově černá',
				'plum'                     => 'švestka',
				'platinum'                 => 'platina',
				'plant'                    => 'rostlina',
				'plane'                    => 'letadlo',
				'plamenak'                 => 'plamenák',
				'plain socks red'          => 'obyčejné ponožky červené',
				'plaid'                    => 'přehoz',
				'pl'                       => 'fialová',
				'pk'                       => 'růžová',
				'pity'                     => 'škoda',
				'pistachio'                => 'pistácie',
				'piskova'                  => 'písková',
				'pisces'                   => 'ryby',
				'pirate'                   => 'pirát',
				'pinkpurple'               => 'růžovofialová',
				'pinkcotton'               => 'růžová bavlna',
				'pinkblue'                 => 'růžovomodrá',
				'pink'                     => 'růžová',
				'pineapple'                => 'ananas',
				'pine green'               => 'borovice zelená',
				'pig'                      => 'prase',
				'picturecolor'             => 'barva obrázku',
				'picture color'            => 'barva obrázku',
				'petticoat only'           => 'pouze spodnička',
				'petrolejova'              => 'petrolejová',
				'pes'                      => 'pes',
				'perspective'              => 'perspektivní',
				'pepa'                     => 'pepa',
				'peony'                    => 'pivoňka',
				'penguin'                  => 'tučňák',
				'pejsek'                   => 'pejsek',
				'pearl pink'               => 'perleťově růžová',
				'peagreen'                 => 'hráškově zelená',
				'peacock blue'             => 'paví modrá',
				'peach'                    => 'broskev',
				'pea green'                => 'hráškově zelená',
				'patchwork'                => 'slátanina',
				'pastelove duhova'         => 'pastelově duhová',
				'parrot'                   => 'papoušek',
				'paq'                      => 'paq',
				'pants'                    => 'kalhoty',
				'pant'                     => 'kalhoty',
				'panda'                    => 'panda',
				'palm purple'              => 'palmově fialová',
				'pajamas'                  => 'pyžama',
				'owl'                      => 'sova',
				'ovoce'                    => 'ovoce',
				'ovce'                     => 'ovce',
				'other'                    => 'jiná',
				'ornage grey'              => 'oranžově šedá',
				'original'                 => 'originál',
				'oranzove'                 => 'oranžová',
				'oranzova'                 => 'oranžová',
				'orangeshort'              => 'oranžové krátké',
				'orangegrey'               => 'oranžově šedá',
				'or'                       => 'oranžová',
				'opicka'                   => 'opička',
				'opice'                    => 'opice',
				'open crotch panties'      => 'otevřené kalhotky v rozkroku',
				'only pendant'             => 'pouze přívěsek',
				'one piece swimsuit'       => 'jednodílné plavky',
				'ombre'                    => 'ombre',
				'olivova'                  => 'olivová',
				'olivegreen'               => 'olivově zelená',
				'olive'                    => 'olivová',
				'old gold'                 => 'staré zlato',
				'ohnivy klic'              => 'ohnivý klíč',
				'ohniva kytara'            => 'ohnivá kytara',
				'od'                       => 'od',
				'octopus'                  => 'chobotnice',
				'ocean'                    => 'oceán',
				'nude'                     => 'akt',
				'noty'                     => 'noty',
				'nostalgic'                => 'nostalgický',
				'nose screw'               => 'nosní šroub',
				'none picture'             => 'žádný obrázek',
				'non waterproof'           => 'ne voděodolný',
				'no engrave'               => 'žádné rytí',
				'nighty lake blue'         => 'noční jezerní modrá',
				'newspaper'                => 'noviny',
				'netopyr'                  => 'netopýr',
				'net red finger'           => 'síťový červený prst',
				'neonove zluta'            => 'neonově žlutá',
				'neonova ruzova'           => 'neonová růže',
				'neon green'               => 'neonově zelená',
				'necklace'                 => 'náhrdelník',
				'navyyellow'               => 'tmavě žlutá',
				'navywhite'                => 'námořnická bílá',
				'navyblue'                 => 'námořnická modrá',
				'navy blue'                => 'námořnická modrá',
				'natural white'            => 'přírodní bílá',
				'national flag'            => 'státní vlajka',
				'nany'                     => 'chůva',
				'nano tape'                => 'nano páska',
				'namornicka'               => 'námořnická',
				'namornicka modr'          => 'námořnická modř',
				'naked pink woman'         => 'nahá růžová žena',
				'nail polish thinner'      => 'ředidlo laku na nehty',
				'na'                       => 'na',
				'mustard'                  => 'hořčice',
				'multicolour'              => 'vícebarevný',
				'multicolor'               => 'vícebarevný',
				'multi'                    => 'vícenásobné',
				'mtee white'               => 'mtee bílá',
				'ms'                       => 'slečna',
				'mr'                       => 'pan',
				'mp'                       => 't.t',
				'mouse'                    => 'myš',
				'motylci'                  => 'motylci',
				'moonstone'                => 'měsíční kámen',
				'moonlight'                => 'měsíční svit',
				'moon'                     => 'měsíc',
				'monkey'                   => 'opice',
				'molv se'                  => 'molv se',
				'modry'                    => 'modrý',
				'modro bila'               => 'modro bílá',
				'modre'                    => 'modré',
				'modre noty'               => 'modre noty',
				'modra'                    => 'modrá',
				'modra tmava'              => 'modrá tmavá',
				'mn black'                 => 'mn černá',
				'mintova'                  => 'mintová',
				'mintgreen'                => 'mátově zelená',
				'mint'                     => 'máta / mátová',
				'minnie'                   => 'minnie',
				'minions'                  => 'přisluhovači',
				'military'                 => 'válečný',
				'midnight blue'            => 'půlnoční modrá',
				'middle blue'              => 'střední modrá',
				'mickey'                   => 'mickey',
				'meteor grey'              => 'meteor šedá',
				'mesh black blue'          => 'síťovina černá modrá',
				'merunkova'                => 'meruňková',
				'mermaid'                  => 'mořská panna',
				'men black'                => 'černá',
				'melounove'                => 'melounové',
				'meloun'                   => 'meloun',
				'medvidek'                 => 'medvídek',
				'medvidci'                 => 'medvidci',
				'medium gray'              => 'středně šedá',
				'mauve'                    => 'nafialovělý',
				'matte black'              => 'matná černá',
				'matna stribrna'           => 'matná stříbrná',
				'maths'                    => 'matematika',
				'matcha green'             => 'zelená matcha',
				'maskakove cerna'          => 'maskákové černá',
				'maskacovegreen'           => 'maskáčovézelené',
				'maskacove zelene'         => 'maskáčové zeleně',
				'maskacova'                => 'maskáčová',
				'maska'                    => 'maska',
				'mask'                     => 'maska',
				'maroon'                   => 'kaštanové',
				'marbling'                 => 'mramorování',
				'marble'                   => 'mramor',
				'maple leaf'               => 'javorový list',
				'mango yellow cotton'      => 'mangově žlutá bavlna',
				'				man'      => 'muž',
				'male'                     => 'mužský',
				'malachite blue'           => 'malachitová modř',
				'maka blue mesh'           => 'maka modrá síťovina',
				'macaron sky blue'         => 'macaron nebesky modrá',
				'lucky red'                => 'šťastná červená',
				'lt purple'                => 'je fialová',
				'low cut black'            => 'nízký střih černé',
				'lovely girl cotton'       => 'krásná holčičí bavlna',
				'lotus color'              => 'lotosová barva',
				'lososova'                 => 'lososová',
				'los'                      => 'los',
				'long top pants'           => 'dlouhé svrchní kalhoty',
				'lol'                      => 'lol',
				'lmw'                      => 'lmw',
				'little red flower'        => 'malý červený květ',
				'listy'                    => 'listy',
				'liska'                    => 'liška',
				'lips'                     => 'rty',
				'lion'                     => 'lev',
				'linght blue'              => 'světle modrá',
				'lined green'              => 'lemované zeleně',
				'line'                     => 'čára',
				'lime green'               => 'limetkově zelená',
				'lilght rose gold'         => 'světle růžové zlato',
				'lilac'                    => 'šeřík',
				'ligth gray'               => 'světle šedá',
				'lightpurple'              => 'světle fialová',
				'lightpink'                => 'světle růžová',
				'lightgrey'                => 'světle šedá',
				'lightgreen'               => 'světle zelená',
				'lightgray'                => 'světle šedá',
				'lightblue'                => 'světle modrá',
				'light blue'               => 'světle modrá',
				'ligh green'               => 'světle zelená',
				'libra'                    => 'váhy',
				'lgy'                      => 'lgy',
				'lgrey'                    => 'šedá',
				'lgray'                    => 'šedá',
				'lg'                       => 'světle zelená',
				'levandulova'              => 'levandulova',
				'lev'                      => 'lev',
				'letters'                  => 'písmena',
				'letter'                   => 'dopis',
				'letadlo'                  => 'letadlo',
				'leopardi'                 => 'leopardi',
				'leopard'                  => 'leopard',
				'leo'                      => 'lev',
				'lenochod'                 => 'lenochod',
				'lemon yellow'             => 'citronově žlutá',
				'left'                     => 'vlevo, odjet',
				'led pant'                 => 'led kalhoty',
				'leaves'                   => 'listy',
				'leather black blue'       => 'kůže černá modrá',
				'leash'                    => 'řemínek',
				'leaher silver green'      => 'kožená stříbrná zelená',
				'leaf'                     => 'list',
				'lblue'                    => 'modrá',
				'				lavender' => 'levandule',
				'lavanda'                  => 'levandule',
				'lava stone'               => 'lávový kámen',
				'laugh'                    => 'smát se',
				'lattice'                  => 'mříž',
				'laser rose gold'          => 'laserové růžové zlato',
				'large'                    => 'velký',
				'lakerblue'                => 'jezerní modrá',
				'laker blue'               => 'jezerní modrá',
				'lakeblue'                 => 'jezerní modrá',
				'lake blue'                => 'jezerní modrá',
				'ladybug'                  => 'slunéčko sedmitečné',
				'lady blue grid'           => 'dáma modrá mřížka',
				'lace black'               => 'krajka černá',
				'labut'                    => 'labuť',
				'kytky'                    => 'kytky',
				'kytara'                   => 'kytara',
				'kvetinova'                => 'květinová',
				'krokodyl'                 => 'krokodyl',
				'kremova'                  => 'krémová',
				'kralovsky modra'          => 'královský modrá',
				'kralovska modr'           => 'královská modr',
				'kralicek'                 => 'králíček',
				'kozoroh'                  => 'kozoroh',
				'koralova'                 => 'koralová',
				'kocka'                    => 'kočka',
				'kocicka'                  => 'kočička',
				'koala'                    => 'koala',
				'kitty'                    => 'koťátko',
				'kiss'                     => 'polibek',
				'king'                     => 'král',
				'kids green model'         => 'dětský zelený model',
				'khika'                    => 'khika',
				'khat stripes'             => 'khat pruhy',
				'khakipink'                => 'khaki',
				'khakie'                   => 'khaki',
				'khakicamo'                => 'khaki',
				'khakiboots'               => 'khaki',
				'khaki'                    => 'khaki',
				'khak'                     => 'khaki',
				'keychain'                 => 'klíčenka',
				'kc gold'                  => 'zlatá',
				'kavova'                   => 'kávová',
				'kaqi'                     => 'khaki',
				'kalhoty'                  => 'kalhoty',
				'kakki'                    => 'haki',
				'kaji bear'                => 'medvěd kaji',
				'kahki'                    => 'kahki',
				'kahaki'                   => 'khaki',
				'jungle camo'              => 'džungle camo',
				'jednorozec'               => 'jednorozec',
				'jasper black h'           => 'jaspis černý h',
				'jasmine'                  => 'jasmín',
				'jarni cerna'              => 'jarní černá',
				'jako obrazek'             => 'jako obrazek',
				'jade green'               => 'nefritově zelená',
				'jachta'                   => 'jachta',
				'ivory'                    => 'ivory',
				'island style'             => 'ostrovním stylu',
				'iron man'                 => 'železný muž',
				'ink green'                => 'inkoustově zelená',
				'imp on horseback'         => 'skřítek na koni',
				'imitation platinum'       => 'imitace platiny',
				'ice blue'                 => 'ledová modř',
				'hvezdicky'                => 'hvězdičky',
				'hvezda'                   => 'hvězda',
				'husky'                    => 'chraplavý',
				'hummingbird'              => 'kolibřík',
				'hulk'                     => 'vrak',
				'hot pink'                 => 'sytě růžová',
				'horse'                    => 'kůň',
				'horcicova'                => 'hořčicová',
				'hoodies'                  => 'mikiny s kapucí',
				'hooded light pink'        => 'světle růžová s kapucí',
				'hong'                     => 'hong',
				'holograficke'             => 'holografické',
				'hole blue'                => 'díra modrá',
				'hnede'                    => 'hnědé',
				'hneda'                    => 'hnědá',
				'his queen'                => 'jeho královna',
				'hight waist blue'         => 'modrý vysoký pas',
				'her king'                 => 'její král',
				'heightened bla'           => 'zvýšené bla',
				'heather mavue'            => 'vřes mavue',
				'heart'                    => 'srdce',
				'he'                       => 'on',
				'hd'                       => 'hd',
				'haze blue'                => 'opar modrá',
				'hat'                      => 'čepice',
				'harry potter hoodie'      => 'mikina s kapucí harry potter',
				'happy'                    => 'šťastný',
				'handsome one love'        => 'pohledná láska',
				'handprint'                => 'otisk ruky',
				'gz black set'             => 'černá sada gz',
				'gy'                       => 'šedá',
				'guitar'                   => 'kytara',
				'grid'                     => 'mřížka',
				'greystripe'               => 'šedý pruh',
				'greysnake'                => 'užovka popelavá',
				'greyred'                  => 'šedě',
				'greyorange'               => 'šedooranžová',
				'greyish white'            => 'šedobílá',
				'greyboots'                => 'šedé boty',
				'greyblue'                 => 'šedomodrá',
				'greyblack'                => 'šedočerná',
				'grey'                     => 'šedá',
				'greensandals'             => 'zelené sandály',
				'greenmen'                 => 'zelení',
				'green'                    => 'zelená',
				'greeen'                   => 'zelená',
				'greeb usb charging'       => 'USB dobíjení',
				'graypink'                 => 'šedorůžová',
				'graymen'                  => 'šedí muži',
				'gray'                     => 'šedá',
				'grass green'              => 'trávově zelená',
				'grapefruit pink'          => 'grapefruitově růžová',
				'grape purple'             => 'hroznově fialová',
				'graffiti'                 => 'graffiti',
				'gradient planet'          => 'planeta s přechodem',
				'grade camouflage'         => 'třídní kamufláž',
				'gr'                       => 'zelená',
				'good camouflage'          => 'dobrá kamufláž',
				'golden'                   => 'zlatá',
				'goden autumn'             => 'boží podzim',
				'gn'                       => 'zelená',
				'glow in dark'             => 'zářit ve tmě',
				'glossy black leather'     => 'lesklá černá kůže',
				'gloss black wood'         => 'lesklé černé dřevo',
				'glass green'              => 'sklo zelené',
				'glacier blue'             => 'ledovcová modrá',
				'girl'                     => 'dívka',
				'giraffe'                  => 'žirafa',
				'ginkgo leaf'              => 'list ginkgo',
				'ginger'                   => 'zrzavá',
				'germany'                  => 'německo',
				'geometry'                 => 'geometrie',
				'gemini'                   => 'blíženci',
				'gd'                       => 'zlatá',
				'gardenia rose'            => 'růže gardénie',
				'fushia'                   => 'fushia',
				'fur black'                => 'kožešina černá',
				'funny'                    => 'legrační',
				'full black'               => 'plná černá',
				'fuchusia'                 => 'fuchusie',
				'fuchsia'                  => 'fuchsie',
				'fruite green a'           => 'ovocná zelená a',
				'fruit green'              => 'ovocně zelená',
				'frosted pattern'          => 'matný vzor',
				'frog'                     => 'žába',
				'froest gray green'        => 'mráz šedozelená',
				'french'                   => 'francouzština',
				'fra bra black'            => 'podprsenka černá',
				'four seasons'             => 'čtyři období',
				'fotoaparat'               => 'fotoaparat',
				'forest green'             => 'lesní zeleň',
				'footprint'                => 'stopa',
				'football'                 => 'fotbal',
				'fog blue'                 => 'mlhově modrá',
				'fluorescent green'        => 'fluorescenční zelená',
				'fluorescence yellow'      => 'fluorescenční žlutá',
				'fluorescein'              => 'fluorescein',
				'fluffy coffee bear'       => 'nadýchaný kávový medvěd',
				'flowers'                  => 'květiny',
				'flower'                   => 'květ',
				'flour cow'                => 'moučná kráva',
				'floral'                   => 'květinový',
				'flip flops beige'         => 'žabky béžové',
				'fleece black blue'        => 'fleecová černo modrá',
				'flat front white'         => 'ploché přední bílé',
				'flamingo'                 => 'plameňák',
				'flag pattern i'           => 'vzor vlajky i',
				'five color flower'        => 'pětibarevný květ',
				'fish'                     => 'ryba',
				'fine vertical stripe'     => 'jemný svislý pruh',
				'filling pp cotton'        => 'výplň pp bavlna',
				'fialovo sediva'           => 'fialovo sediva',
				'fialove'                  => 'fialová',
				'fialova'                  => 'fialová',
				'fialova svetla'           => 'fialová světla',
				'fialkove'                 => 'fialková',
				'fialkova'                 => 'fialková',
				'female'                   => 'ženský',
				'feather'                  => 'pírko',
				'fds'                      => 'fds',
				'fashion black'            => 'módní černá',
				'fairy powder'             => 'pohádkový prášek',
				'eyes'                     => 'oči',
				'eyelash unicorn pink'     => 'řasa jednorožec růžová',
				'eu plug charger'          => 'eu nabíječka',
				'erduo gray'               => 'šedá',
				'england flag'             => 'anglická vlajka',
				'emerald green'            => 'smaragdová zeleň',
				'embroidered'              => 'vyšívané',
				'elsa'                     => 'elsa',
				'elephant'                 => 'slon',
				'ee'                       => 'ee',
				'ecru'                     => 'ecru',
				'eclipse'                  => 'zatmění',
				'earth yellow'             => 'země žlutá',
				'eagle'                    => 'orel',
				'dusty pink'               => 'prachově růžová',
				'dusk'                     => 'soumrak',
				'duhova'                   => 'duhová',
				'duha'                     => 'duha',
				'duck'                     => 'kachna',
				'duch s rouskou'           => 'duch s rouskou',
				'dress b'                  => 'šaty b',
				'dream blue flower'        => 'vysněný modrý květ',
				'drak blue'                => 'drak modrá',
				'dragonfly blue'           => 'vážka modrá',
				'dragon'                   => 'drak',
				'dots'                     => 'tečky',
				'dot'                      => 'tečka',
				'donut'                    => 'kobliha',
				'dolphin'                  => 'delfín',
				'dolores'                  => 'dolores',
				'dog'                      => 'pes',
				'dlsjinbl'                 => 'dlsjinbl',
				'dlshei'                   => 'dlshei',
				'dlsenjoy'                 => 'dlsenjoy',
				'dlsbai'                   => 'dlsbai',
				'dle obrazku'              => 'dle obrazu',
				'dkgreen'                  => 'dkgreen',
				'dk pink'                  => 'dk růžová',
				'disdain'                  => 'pohrdání',
				'dinosaurus'               => 'dinosaurus',
				'dinosaurs'                => 'dinosauři',
				'dinosauri'                => 'dinosauri',
				'dinosaur'                 => 'dinosaurus',
				'dino'                     => 'dino',
				'dimmable with remote'     => 'stmívatelné dálkovým ovládáním',
				'digital'                  => 'digitální',
				'diasaur'                  => 'diasaur',
				'diamond pink'             => 'diamantově růžová',
				'diamantova modra'         => 'diamantová modrá',
				'dgy'                      => 'šedá',
				'dgray'                    => 'šedá',
				'devil'                    => 'ďábel',
				'desert camo'              => 'pouštní kamufláž',
				'dense forest green'       => 'hustá lesní zeleň',
				'denim blue'               => 'džínová modrá',
				'demon'                    => 'démon',
				'deer'                     => 'jelen',
				'deepgray'                 => 'tmavě šedá',
				'deepblue'                 => 'tmavě modrá',
				'deep blue'                => 'tmavě modrá',
				'darkyellow'               => 'tmavě žlutá',
				'darkstar'                 => 'tmavá hvězda',
				'darkpink'                 => 'tmavě růžová',
				'darkgreyblack'            => 'tmavě šedočerná',
				'darkgrey'                 => 'tmavě šedá',
				'darkgreen'                => 'tmavozelený',
				'darkgray'                 => 'tmavě šedá',
				'darkblue'                 => 'tmavě modrá',
				'dark blue'                => 'tmavě modrá',
				'dandelion'                => 'pampeliška',
				'daisy'                    => 'sedmikráska',
				'cyan'                     => 'tyrkysová',
				'cute'                     => 'roztomilý',
				'curtain tulle'            => 'záclonový tyl',
				'crystal transparent'      => 'krystal transparentní',
				'crown'                    => 'koruna',
				'crotchless panties'       => 'kalhotky bez rozkroku',
				'crocodile'                => 'krokodýl',
				'crimson'                  => 'karmínový',
				'creative wave marble'     => 'kreativní vlnový mramor',
				'creamy white'             => 'krémově bílá',
				'cream'                    => 'krém',
				'crayon shin chan'         => 'pastelka shin chan',
				'cranberry'                => 'brusinka',
				'crab'                     => 'krab',
				'coyot'                    => 'kojot',
				'cowboy blue'              => 'kovbojská modrá',
				'cow'                      => 'kráva',
				'cosmos flower'            => 'vesmírný květ',
				'coral red'                => 'korálově červená',
				'contrast flowers'         => 'kontrastní květiny',
				'colorful'                 => 'barevná',
				'colored star unicorn'     => 'barevný hvězdný jednorožec',
				'colorblue   black'        => 'barva modrá černá',
				'cold white'               => 'studená bílá',
				'coffer'                   => 'truhla',
				'coffee'                   => 'kávová',
				'coffe'                    => 'káva',
				'coconuttree'              => 'kokosový strom',
				'coconut tree'             => 'kokosový strom',
				'cloth'                    => 'tkanina',
				'close eye panda'          => 'zavřít oko panda',
				'cloak'                    => 'plášť',
				'clear'                    => 'průhledná',
				'classic black'            => 'klasická černá',
				'claret'                   => 'bordó',
				'cinderella'               => 'popelka',
				'cihlova'                  => 'cihlová',
				'chrysanthemum'            => 'chryzantéma',
				'chrome color'             => 'chromová barva',
				'christmas red'            => 'vánoční červená',
				'chocolate'                => 'čokoládová',
				'chinese deep blue'        => 'čínská tmavě modrá',
				'china'                    => 'čína',
				'chick'                    => 'kuřátko',
				'chestnut'                 => 'kaštan',
				'cherry purple'            => 'třešňově fialová',
				'charming blue'            => 'okouzlující modrá',
				'charmander'               => 'šarmander',
				'charcoal'                 => 'dřevěné uhlí',
				'changeable'               => 'měnitelný',
				'champange'                => 'šampaňské',
				'champagne'                => 'šampaňské',
				'champage'                 => 'šampaňské',
				'chain'                    => 'řetěz',
				'cgray'                    => 'šedá',
				'cf'                       => 'srov',
				'cerveno zlate'            => 'červené zlaté',
				'cervene'                  => 'červené',
				'cervena'                  => 'červená',
				'cerny'                    => 'černá',
				'cernobila'                => 'černobílá',
				'cerno bila'               => 'černo bílá',
				'cerne'                    => 'černá',
				'cerna'                    => 'černá',
				'celo cerna'               => 'celá černá',
				'celadon'                  => 'seladon',
				'cattle'                   => 'dobytek',
				'cat'                      => 'kočka',
				'castle'                   => 'hrad',
				'cartoon'                  => 'kreslená pohádka',
				'cars'                     => 'auta',
				'carrot'                   => 'mrkev',
				'carmine'                  => 'karmín',
				'cardigans'                => 'kardigany',
				'cardigan and scarf'       => 'cardigan a šátek',
				'caramel'                  => 'karamel',
				'car'                      => 'auto',
				'captain america'          => 'kapitán amerika',
				'capricorn'                => 'kozoroh',
				'capitan america'          => 'kapitán amerika',
				'candy purple'             => 'cukroví fialová',
				'cancer'                   => 'rakovina',
				'canada'                   => 'kanada',
				'camouflage'               => 'maskovací / maskáčová / camouflage',
				'camo'                     => 'maskáčová / camo',
				'cameo'                    => 'portrét',
				'camellia red'             => 'kamélie červená',
				'camel'                    => 'velbloud',
				'calf  length butterf'     => 'motýl délky po lýtka',
				'cai blcak'                => 'cai blcak',
				'cactus'                   => 'kaktus',
				'bw'                       => 'černobílá',
				'butterfly'                => 'motýl',
				'burgundy'                 => 'burgundy',
				'bule'                     => 'modrá / bule',
				'buldocek'                 => 'buldoček',
				'bulbasaur'                => 'bulbasaur',
				'bugs bunny'               => 'bugs bunny',
				'bublinky'                 => 'bublinky',
				'bu'                       => 'modrá',
				'brownsandals'             => 'hnědé sandály',
				'brownboots'               => 'hnědé boty',
				'brown'                    => 'hnědá',
				'broskvova'                => 'broskvová',
				'bronzova'                 => 'bronzová',
				'bronze'                   => 'bronzová',
				'brontosaurus'             => 'brontosaurus',
				'britska lebka'            => 'britská lebka',
				'british flag'             => 'britská vlajka',
				'brightyellow'             => 'světle žlutá',
				'brightblue'               => 'zářivě modrá',
				'bright pink'              => 'světle růžová',
				'brick red'                => 'cihlová červená',
				'breathable'               => 'prodyšný',
				'brazil'                   => 'brazílie',
				'boys'                     => 'chlapci',
				'boy'                      => 'chlapec',
				'boluo'                    => 'boluo',
				'boho'                     => 'boho',
				'bodysuits nude pink'      => 'body nahá růžová',
				'bodysuit light green'     => 'body světle zelená',
				'boat'                     => 'loď',
				'bn'                       => 'hnědá',
				'bluish purple'            => 'modrofialová',
				'bluewhite'                => 'modrá bílá',
				'bluepurple'               => 'modrofialová',
				'bluemen'                  => 'modrá',
				'bluegrey'                 => 'modrošedá',
				'bluegreen'                => 'modrá zelená',
				'blueboots'                => 'blueboots',
				'blueblackdyinwenhon'      => 'modro černá',
				'blueblackdyinwencai'      => 'modro černá',
				'blueberry'                => 'borůvka',
				'blue'                     => 'modrá',
				'blu'                      => 'modrá',
				'blonde pink'              => 'blond růžová',
				'blk'                      => 'černá',
				'blcak'                    => 'černá',
				'blankytne modra'          => 'blankytně modrá',
				'blank'                    => 'prázdný',
				'blanco'                   => 'blanco',
				'blak'                     => 'černá',
				'blackwhite'               => 'černá bílá',
				'blackthin'                => 'černá',
				'blackstripe'              => 'černý pruh',
				'blackstars'               => 'černé hvězdy',
				'blackred'                 => 'černá červená',
				'blackpurple'              => 'černofialová',
				'blackpearl'               => 'černá perla',
				'blackno belt'             => 'pásek blackno',
				'blackmen'                 => 'černá',
				'blackish green'           => 'černozelená',
				'blackgrey'                => 'černošedý',
				'blackgray'                => 'černošedá',
				'blackgold purple'         => 'černozlatá fialová',
				'blackflower'              => 'černokvět',
				'blacke'                   => 'černá',
				'blackcolor'               => 'černá barva',
				'blackcamo'                => 'černá',
				'blackboots'               => 'černé boty',
				'blackblue'                => 'černomodrá',
				'blackblackdyinwenhon'     => 'černá',
				'blackblackdyinwencai'     => 'černá',
				'blackbag black'           => 'černá',
				'blackasiansize'           => 'černá',
				'blackandwhite'            => 'černý a bílý',
				'blackaa'                  => 'černá',
				'blacka'                   => 'černá',
				'black'                    => 'černá',
				'bla'                      => 'bla',
				'bl'                       => 'modrá / černá',
				'bkleop'                   => 'bkleop',
				'bk'                       => 'černá',
				'birthday lips'            => 'narozeninové rty',
				'bird'                     => 'pták',
				'bilo modra'               => 'bílo modrá',
				'bilo cervena'             => 'bílo červená',
				'bila'                     => 'bílá',
				'bikini purple'            => 'fialové bikiny',
				'bigredboots'              => 'velké červené boty',
				'bigred'                   => 'velká červená',
				'big red'                  => 'velká červená',
				'bibs mint green'          => 'bryndáčky mátově zelené',
				'bgreen'                   => 'zelená',
				'bg'                       => 'béžová',
				'bezove'                   => 'béžová',
				'bezova'                   => 'béžová',
				'bezova khaki'             => 'béžová khaki',
				'bez kozisku cerne'        => 'bez kožíšku',
				'berry color'              => 'barva bobule',
				'belle dress'              => 'belle šaty',
				'beigepearl'               => 'béžová perla',
				'beigeflower'              => 'béžový květ',
				'beida'                    => 'beida',
				'bee'                      => 'včela',
				'beatiful bedding'         => 'nádherné povlečení',
				'bear'                     => 'medvěd',
				'beanred'                  => 'fazolový',
				'bean paste'               => 'fazolová',
				'bckurky'                  => 'bckurky',
				'bbeige'                   => 'béžová',
				'batman'                   => 'batman',
				'batikovane cerne'         => 'batikovane cerne',
				'batika'                   => 'batika',
				'bat'                      => 'netopýr',
				'basketball'               => 'basketball',
				'barevny'                  => 'barevny',
				'barevne'                  => 'barevné',
				'barevna'                  => 'barevná',
				'bandanna'                 => 'šátek',
				'banana'                   => 'banán',
				'balloon'                  => 'balón',
				'balck'                    => 'balck',
				'bag black'                => 'taška černá',
				'back'                     => 'zadní',
				'baby romper'              => 'dětské dudlík',
				'azure bold striped'       => 'blankytně tučně pruhované',
				'awine red'                => 'vínově červená',
				'awhite'                   => 'bílá',
				'avocado'                  => 'avokádo',
				'autumn black'             => 'podzimní černá',
				'auto'                     => 'auto',
				'auspicious red'           => 'příznivá červená',
				'auburn'                   => 'kaštanová',
				'at the picture'           => 'na obrázku',
				'astronaut'                => 'astronaut',
				'asphalt'                  => 'asfalt',
				'asky blue'                => 'nebesky modrá',
				'as picture'               => 'jako obrázek',
				'arrow silver black'       => 'šipka stříbrná černá',
				'arose'                    => 'vznikl',
				'armygreen'                => 'vojenská zelená',
				'army green'               => 'vojenská zelená',
				'armpit should pad'        => 'podpaží by mělo vycpávat',
				'armg green'               => 'armg zelená',
				'armadni zelena'           => 'armádní zelená',
				'aries'                    => 'beran',
				'aquarius'                 => 'vodnář',
				'aqua blue'                => 'aqua modrá',
				'apricote'                 => 'meruňková',
				'apricot'                  => 'meruňka',
				'appricot'                 => 'meruňka',
				'apply green'              => 'aplikovat zelenou',
				'apple green'              => 'zelené jablko',
				'app remote control'       => 'dálkové ovládání aplikace',
				'apale green'              => 'bledě zelená',
				'antique silver plated'    => 'starožitné postříbřené',
				'anna'                     => 'anna',
				'animals'                  => 'zvířata',
				'animal paradise'          => 'zvířecí ráj',
				'angry'                    => 'rozzlobený',
				'angel'                    => 'anděl',
				'ancient silver'           => 'starověké stříbro',
				'anavy blue'               => 'modrá',
				'ananas'                   => 'ananas',
				'amy green'                => 'zelená',
				'amry green'               => 'zelená',
				'amongus clothes set'      => 'sada oblečení',
				'amethyst'                 => 'ametyst',
				'amaranth'                 => 'amarant',
				'all black'                => 'všechno černé',
				'alight pink'              => 'světle růžové',
				'airplane'                 => 'letoun',
				'ag'                       => 'aqua modrá',
				'adult black green'        => 'dospělý černozelený',
				'aa'                       => 'aqua modrá',
				'lichtblauw'               => 'světle modrá',
				'donkerblauw'              => 'tmavě modrá',
				'hemelsblauw'              => 'nebesky modrá',
				'middernachtblauw'         => 'polonoční modrá',
				'navyblauw'                => 'námořnická modrá',
				'azuur'                    => 'azurová',
				'turkooisblauw'            => 'tyrkysově modrá',
				'mintgroen'                => 'mátová',
				'appelgroen'               => 'jablkově zelená',
				'limoengroen'              => 'limetková',
				'olijfgroen'               => 'olivově zelená',
				'legergroen'               => 'armádní zelená',
				'jagergroen'               => 'lovecká zelená',
				'chartreusegroen'          => 'chartreuská',
				'lime'                     => 'limetková',
				'goudgeel'                 => 'zlatavá',
				'karamel'                  => 'karamelová',
				'oker'                     => 'okrová',
				'oranjerood'               => 'oranžovočervená',
				'koraalrood'               => 'korálově červená',
				'robijnrood'               => 'rubínová',
				'bordeauxrood'             => 'bordová',
				'wijnrood'                 => 'vínová',
				'kastanje'                 => 'kaštanová',
				'rozerood'                 => 'růžovočervená',
				'fuchsiaroze'              => 'fuchsiová',
				'hotpink'                  => 'výrazně růžová',
				'orchidee'                 => 'orchidejová',
				'pruim'                    => 'švestková',
				'ultraviolet'              => 'ultrafialová',
				'lavendelblauw'            => 'levandulově modrá',
				'koffie'                   => 'kávová',
				'cacao'                    => 'kakaová',
				'hazelnoot'                => 'lískooříšková',
				'kaneel'                   => 'skořicová',
				'gember'                   => 'zázvorová',
				'sepia'                    => 'sépiová'
			);
			if ( $translate[ $color_replace ] ) {
				return $translate[ $color_replace ];
			} else {
				return $color;
			}
		}

		public function size_translate( $size ) {
			$sizes = [
				"3m"       => "3 měsíce",
				"6m"       => "6 měsíců",
				"9m"       => "9 měsíců",
				"12m"      => "12 měsíců",
				"18m"      => "18 měsíců",
				"24m"      => "24 měsíců",
				"2t"       => "2 roky",
				"3t"       => "3 roky",
				"4t"       => "4 roky",
				"5t"       => "5 roky",
				"6t"       => "6 let",
				"7t"       => "7 let",
				"8t"       => "8 let",
				"9t"       => "9 let",
				"10t"      => "10 let",
				"11t"      => "11 let",
				"12t"      => "12 let",
				"13t"      => "13 let",
				"14t"      => "14 let",
				"15t"      => "15 let",
				"one-size" => "univerzální velikost",
				"uni"      => "univerzální velikost",
				"iphone"   => "iPhone",
			];

			if ( $sizes[ $size ] ) {
				return $sizes[ $size ];
			} else {
				return $size;
			}
		}

		public function remove_strings( $string ) {

			$to_remove = array( 'china', 'for' );


			foreach ( $to_remove as $word ) {
				$string = str_replace( $word, '', $string );
			}

			return $string;
		}

		public function possible_attributes_sizes() {
			return implode( '|', array(
				'siz',
				'veliko',
				'size',
				'grosse',
				'grose',
				'pa_axis-body',
				'pa_ballon-size',
				'pa_bands-size',
				'pa_electra-velikost',
				'pa_gift-bag-size',
				'pa_gift-box-size',
				'pa_gloves-size',
				'pa_hat-size',
				'pa_christmas-hat-size',
				'pa_kid-size',
				'pa_kid-us-size',
				'pa_king-velikost',
				'pa_luggage-size',
				'pa_plate-size',
				'pa_product-size',
				'pa_ring-size',
				'pa_sheet-size',
				'pa_shoe-size',
				'pa_size',
				'pa_size-inch',
				'pa_size-shape-style',
				'pa_sizecm',
				'pa_snowflake-size',
				'pa_sticker-size',
				'pa_the-king-velikost',
				'pa_the-queen-velikost',
				'pa_tweeter-size',
				'pa_tweeter-size-set-type',
				'pa_us-size',
				'pa_veikost',
				'pa_vel',
				'pa_veleikost',
				'pa_velikoist',
				'pa_velikos',
				'pa_velikosat',
				'pa_velikosst',
				'pa_velikost',
				'pa_velikost-barva',
				'pa_velikost-boty',
				'pa_velikost-cm',
				'pa_velikost-detsky',
				'pa_velikost-eur',
				'pa_velikost-kosicku',
				'pa_velikost-l',
				'pa_velikost-l-44',
				'pa_velikost-m-41',
				'pa_velikost-s',
				'pa_velikost-s-38',
				'pa_velikost-satu',
				'pa_velikost-serie',
				'pa_velikost-us',
				'pa_velikost-xl',
				'pa_velikost-xl-46',
				'pa_velikost-xs-35',
				'pa_velikost12',
				'pa_velikost2',
				'pa_velikostcm',
				'pa_velikosti',
				'pa_velikostt',
				'pa_velikosz',
				'pa_velikoti',
				'pa_veliksot',
				'pa_veliskost',
				'pa_velka',
				'pa_velkost',
				'pa_velky',
				'pa_vellikost',
				'pa_veloikost',
				'pa_vvelikost',
				'pa_woofer-size-full-rang',
				'bands-size',
				'cup-size',
				'child-size',
				'kid-size',
				'maternity-size',
				'pet-size',
				'pick-size',
				'ring-size',
				'sheet-size',
				'shoe-size',
				'size',
				'size-inch',
				'sizecm',
				'pa_detska-velikost',
				'pa_cup-size',
				'pa_ballon-size',
				'pa_bands-size',
				'pa_belt-length',
				'child-size',
				'delka',
				'kid-size',
				'pa_gloves-size',
				'pa_kid-size',
				'pa_luggage-size',
				'pa_maternity-size',
				'pa_pick-size',
				'pa_plate-size',
				'pa_product-size',
				'pa_ring-size',
				'pa_sheet-size',
				'pa_shoe-size',
				'pa_size',
				'pa_size-inch',
				'pa_sizecm',
				'pa_specification',
				'pa_sticker-size',
				'pa_stretched-length',
				'pa_the-king-velikost',
				'pa_the-king-velkost',
				'pa_the-queen-velikost',
				'pa_the-queen-velkost',
				'pa_us-size',
				'pa_velikosat',
				'pa_velikost',
				'pa_velikost-pasma',
				'pa_velikost-pasu',
				'pa_velikost-prstenu',
				'pa_velikosti',
				'pa_velikostsize',
				'pa_veliksot',
				'pa_velkost',
				'pa_velkost-nohy',
				'pa_velkost-podpatku',
				'pa_velkost-postavy',
				'pa_vellikost',
				'pa_veloikost',
				'pa_vvelikost',
				'ring-size',
				'shoe-size',
				'size',
				'size-inch',
				'velikost',
				'velkost',
				'pa_velikost-kosicku',
				'pa_cup-size',
				'pa_velikost-obvodu',
				'pa_velikost-podpatku',
				'veli'
			) );
		}

		public function possible_attributes_color() {
			return implode( '|', array(
				'barv',
				'farb',
				'pa_band-color',
				'pa_barvy',
				'pa_bava',
				'pa_bavra',
				'pa_body-color',
				'pa_brava',
				'pa_color',
				'pa_color-frame',
				'pa_color-name',
				'pa_color-temperature',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_f',
				'pa_farba',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_metal-color',
				'band-color',
				'barva',
				'barva-led',
				'barva-osvetleni',
				'body-color',
				'color',
				'color-name',
				'emitting-color',
				'frame-color',
				'gem-color',
				'handle-color',
				'lampshade-color',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'barva',
				'color',
				'color-name',
				'body-color',
				'emitting-color',
				'farba',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'pa_barav',
				'pa_barava',
				'pa_barva',
				'pa_barva-bryli',
				'pa_barva-cocek',
				'pa_barva-cocky',
				'pa_barva-led',
				'pa_barva-obroucek',
				'pa_barva-ramu',
				'pa_barva-sklicek',
				'pa_barva-stetcu',
				'pa_barva-varianta',
				'pa_barvy',
				'pa_bavra',
				'pa_bila',
				'pa_bila-s-motivy',
				'pa_body-color',
				'pa_brava',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_material',
				'pa_metal-color',
				'pa_color-name',
				'pa_color',
				'pa_color-frame',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_farba',
				'pa_farba-a-velkost',
				'pa_farba-podsvietenia',
				'pa_farby',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'band-color',
				'barva-led',
				'body-color',
				'color-name',
				'color',
				'emitting-color',
				'frame-color',
				'gem-color',
				'handle-color',
				'lampshade-color',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'pa_band-color',
				'pa_bava',
				'pa_bavra',
				'pa_body-color',
				'pa_brava',
				'pa_color-frame',
				'pa_color-name',
				'pa_color-temperature',
				'pa_color',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_f',
				'pa_farba',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_metal-color',
				'barva',
				'farba',
				'pa_barav',
				'pa_barava',
				'pa_barva-varianta',
				'pa_barva',
				'pa_barvy',
				'pa_bila-s-motivy',
				'pa_bila',
				'pa_farba-a-velkost',
				'pa_farba-podsvietenia',
				'pa_farby',
				'pa_size-emitting-color',
				'colo'
			) );
		}

	}
}
