<?php

if ( ! class_exists( 'WPCFeedStatics' ) ) {

	class WPCFeedStatics {
		private static $instance; //singleton instance
		private $prefix = 'WPCFeedStatics';

		public static function get_instance() {
			if ( self::$instance === null ) {
				self::$instance = new self;
			}

			return self::$instance;
		}

		public function color_translate( $color ) {
			$translate = array(
				'black'                 => 'černá',
				'white'                 => 'bílá',
				'blue'                  => 'modrá',
				'red'                   => 'červené',
				'pink'                  => 'růžová',
				'gray'                  => 'šedá',
				'green'                 => 'zelená',
				'yellow'                => 'žlutá',
				'černá'                 => 'černá',
				'khaki'                 => 'khaki',
				'purple'                => 'fialová',
				'brown'                 => 'hnědá',
				'orange'                => 'oranžová',
				'bílá'                  => 'bílá',
				'modrá'                 => 'modrá',
				'beige'                 => 'béžová',
				'růžová'                => 'růžová',
				'červená'               => 'červená',
				'grey'                  => 'šedá',
				'zelená'                => 'zelená',
				'šedá'                  => 'šedá',
				'gold'                  => 'zlatá',
				'silver'                => 'stříbrná',
				'army green'            => 'vojenská zelená',
				'navy blue'             => 'námořnická modrá',
				'burgundy'              => 'burgundy',
				'žlutá'                 => 'žlutá',
				'wine red'              => 'červené víno',
				'sky blue'              => 'modrá obloha',
				'coffee'                => 'kávová',
				'dark blue'             => 'tmavě modrá',
				'béžová'                => 'béžová',
				'light blue'            => 'světle modrá',
				'auburn'                => 'kaštanová',
				'hnědá'                 => 'hnědá',
				'fialová'               => 'fialová',
				'rose red'              => 'růže červená',
				'apricot'               => 'meruňka',
				'tmave modra'           => 'tmavá modrá',
				'oranžová'              => 'oranžová',
				'vínová'                => 'vínová',
				'ivory'                 => 'ivory',
				'multi'                 => 'vícenásobné',
				'royal blue'            => 'královská modrá',
				'bk'                    => 'černá',
				'lavender'              => 'levandule',
				'picture color'         => 'barva obrázku',
				'svetle modra'          => 'světle modrá',
				'leopard'               => 'leopard',
				'champagne'             => 'šampaňské',
				'camel'                 => 'velbloud',
				'stříbrná'              => 'stříbrná',
				'zlatá'                 => 'zlatá',
				'armygreen'             => 'vojenská zelená',
				'leather black blue'    => 'kůže černá modrá',
				'fuchsia'               => 'fuchsie',
				'brick red'             => 'cihlová červená',
				'as picture'            => 'jako obrázek',
				'rd'                    => 'červená',
				'bu'                    => 'modrá',
				'lake blue'             => 'jezerní modrá',
				'pk'                    => 'růžová',
				'šedivá'                => 'šedivá',
				'deep blue'             => 'tmavě modrá',
				'haze blue'             => 'opar modrá',
				'camouflage'            => 'maskovací / maskáčová / camouflage',
				'claret'                => 'bordó',
				'gy'                    => 'šedá',
				'tmavě modrá'           => 'tmavě modrá',
				'darkblue'              => 'tmavě modrá',
				'multicolor'            => 'vícebarevný',
				'watermelon red'        => 'melounová červená',
				'clear'                 => 'průhledná',
				'colorful'              => 'barevná',
				'gn'                    => 'zelená',
				'fluorescent green'     => 'fluorescenční zelená',
				'vinova'                => 'vinová',
				'hot pink'              => 'sytě růžová',
				'chocolate'             => 'čokoládová',
				'golden'                => 'zlatá',
				'dle obrazku'           => 'dle obrazu',
				'creamy white'          => 'krémově bílá',
				'other'                 => 'jiná',
				'mint'                  => 'máta / mátová',
				'mesh black blue'       => 'síťovina černá modrá',
				'steel black blue'      => 'ocelově černá modrá',
				'transparent'           => 'průhledná / transparentní',
				'peacock blue'          => 'paví modrá',
				'men black'             => 'černá',
				'wh'                    => 'bílá',
				'sapphire'              => 'safírová',
				'černé'                 => 'černá',
				'violet'                => 'fialová',
				'světle modrá'          => 'světle modrá',
				'nude'                  => 'akt',
				'rainbow'               => 'duha',
				'skin'                  => 'kůže',
				'ye'                    => 'žlutá',
				'caramel'               => 'karamel',
				'skyblue'               => 'modrá obloha',
				'kc gold'               => 'zlatá',
				'turquoise'             => 'tyrkysová',
				'sliver'                => 'střípek',
				'warm white'            => 'teplá bílá',
				'the picture color'     => 'barva obrázku',
				'bule'                  => 'modrá / bule',
				'bronze'                => 'bronzová',
				'maroon'                => 'kaštanové',
				'cyan'                  => 'tyrkysová',
				'winered'               => 'červené víno',
				'bear'                  => 'medvěd',
				'krémová'               => 'krémová',
				'khak'                  => 'khaki',
				'darkgrey'              => 'tmavě šedá',
				'only pendant'          => 'pouze přívěsek',
				'tyrkysová'             => 'tyrkysová',
				'panda'                 => 'panda',
				'coral red'             => 'korálově červená',
				'flower'                => 'květ',
				'pp'                    => 'fialová',
				'stripe'                => 'proužek',
				'peach'                 => 'broskev',
				'all black'             => 'všechno černé',
				'dinosaur'              => 'dinosaurus',
				'rabbit'                => 'králičí',
				'wt'                    => 'bílá',
				'bean paste'            => 'fazolová',
				'namornicka modr'       => 'námořnická modř',
				'cold white'            => 'studená bílá',
				'ag'                    => 'aqua modrá',
				'navyblue'              => 'námořnická modrá',
				'grass green'           => 'trávově zelená',
				'cosmos flower'         => 'vesmírný květ',
				'yw'                    => 'žlutá',
				'unicorn'               => 'jednorožec',
				'denim blue'            => 'džínová modrá',
				'tulle'                 => 'tyl',
				'star'                  => 'hvězda',
				'print'                 => 'tisk',
				'modra tmava'           => 'modrá tmavá',
				'modré'                 => 'modré',
				'lemon yellow'          => 'citronově žlutá',
				'telova'                => 'tělová',
				'růžové'                => 'růžové',
				'darkgray'              => 'tmavě šedá',
				'blackmen'              => 'černá',
				'hoodies'               => 'mikiny s kapucí',
				'bluemen'               => 'modrá',
				'rosered'               => 'růže červená',
				'rosy red'              => 'růžově červená',
				'skybluemen'            => 'skybluemen',
				'graymen'               => 'šedí muži',
				'greenmen'              => 'zelení',
				'cream'                 => 'krém',
				'frosted pattern'       => 'matný vzor',
				'olive'                 => 'olivová',
				'matcha green'          => 'zelená matcha',
				'mustard'               => 'hořčice',
				'červené'               => 'červené',
				'bw'                    => 'černobílá',
				'floral'                => 'květinový',
				'lion'                  => 'lev',
				'seda tmava'            => 'seda tmavá',
				'ginger'                => 'zrzavá',
				'anna'                  => 'anna',
				'spiderman'             => 'pavoučí muž',
				'snowman'               => 'sněhulák',
				'bg'                    => 'béžová',
				'hole blue'             => 'díra modrá',
				'cat'                   => 'kočka',
				'flamingo'              => 'plameňák',
				'sweatshirt'            => 'mikina',
				'zip hoodies'           => 'mikina na zip',
				'bl'                    => 'modrá / černá',
				'tiger'                 => 'tygr',
				'curtain tulle'         => 'záclonový tyl',
				'whitemen'              => 'bílá',
				'antique silver plated' => 'starožitné postříbřené',
				'yellowmen'             => 'žlutá',
				'zelené'                => 'zelená',
				'elsa'                  => 'elsa',
				'forest green'          => 'lesní zeleň',
				'pig'                   => 'prase',
				'santa claus'           => 'santa claus',
				'solid black'           => 'černá',
				'graffiti'              => 'graffiti',
				'minnie'                => 'minnie',
				'tan'                   => 'opálení',
				'sada'                  => 'sada',
				'blk'                   => 'černá',
				'pineapple'             => 'ananas',
				'redwine'               => 'červené víno',
				'strawberry'            => 'jahoda',
				'malachite blue'        => 'malachitová modř',
				'emerald green'         => 'smaragdová zeleň',
				'heart'                 => 'srdce',
				'zebra'                 => 'zebra',
				'no engrave'            => 'žádné rytí',
				'fruit green'           => 'ovocně zelená',
				'striped'               => 'pruhová',
				'plum'                  => 'švestka',
				'butterfly'             => 'motýl',
				'dusty pink'            => 'prachově růžová',
				'set'                   => 'set',
				'lightgray'             => 'světle šedá',
				'šedé'                  => 'šedé',
				'bn'                    => 'hnědá',
				'royalblue'             => 'královská modrá',
				'lightgrey'             => 'světle šedá',
				'cerny'                 => 'černá',
				'queen'                 => 'královna',
				'deepblue'              => 'tmavě modrá',
				'gr'                    => 'zelená',
				'bbeige'                => 'béžová',
				'letter'                => 'dopis',
				'mickey'                => 'mickey',
				'sand'                  => 'písek',
				'lightblue'             => 'světle modrá',
				'cgray'                 => 'šedá',
				'big red'               => 'velká červená',
				'bright pink'           => 'světle růžová',
				'armadni zelena'        => 'armádní zelená',
				'camo'                  => 'maskáčová / camo',
				'mintova'               => 'mintová',
				'marble'                => 'mramor',
				'fuchusia'              => 'fuchusie',
				'hořčicová'             => 'hořčicová',
				'duck'                  => 'kachna',
				'kaqi'                  => 'khaki',
				'plaid'                 => 'přehoz',
				'batman'                => 'batman',
				'girl'                  => 'dívka',
				'cow'                   => 'kráva',
				'dog'                   => 'pes',
				'darkpink'              => 'tmavě růžová',
				'barevná'               => 'barevná',
				'pure black'            => 'čistě černá',
				'kvetinova'             => 'květinová',
				'matte black'           => 'matná černá',
				'silvery'               => 'stříbrná',
				'whlite'                => 'bílá',
				'blackwhite'            => 'černá bílá',
				'superman'              => 'superman',
				'ligh green'            => 'světle zelená',
				'ts'                    => 'ts',
				'giraffe'               => 'žirafa',
				'chrysanthemum'         => 'chryzantéma',
				'neon green'            => 'neonově zelená',
				'greyish white'         => 'šedobílá',
				'ultra tenke'           => 'ultra tenke',
				'blackish green'        => 'černozelená',
				'tender pink'           => 'něžná růžová',
				'frog'                  => 'žába',
				'blackred'              => 'černá červená',
				'deer'                  => 'jelen',
				'magenta'               => 'purpurová',
				'rc changeable'         => 'rc měnitelný',
				'patchwork'             => 'slátanina',
				'owl'                   => 'sova',
				'zlute'                 => 'žlutá',
				'fialkova'              => 'fialková',
				'leaf'                  => 'list',
				'moon'                  => 'měsíc',
				'or'                    => 'oranžová',
				'písková'               => 'písková',
				'lg'                    => 'světle zelená',
				'lucky red'             => 'šťastná červená',
				'dot'                   => 'tečka',
				'pl'                    => 'fialová',
				'lt purple'             => 'je fialová',
				'levandulova'           => 'levandulova',
				'random color'          => 'náhodná barva',
				'retro'                 => 'retro',
				'yl'                    => 'žlutá',
				'ananas'                => 'ananas',
				'diamantova modra'      => 'diamantová modrá',
				'one piece swimsuit'    => 'jednodílné plavky',
				'mermaid'               => 'mořská panna',
				'grid'                  => 'mřížka',
				'safirova modra'        => 'safirova modra',
				'elephant'              => 'slon',
				'pup'                   => 'štěně',
				'mp'                    => 't.t',
				'darkgreen'             => 'tmavozelený',
				'vícebarevná'           => 'vícebarevná',
				'iron man'              => 'železný muž',
				'coffe'                 => 'káva',
				'krokodyl'              => 'krokodyl',
				'tiffany blue'          => 'tiffany modrá',
				'hong'                  => 'hong',
				'kralovska modr'        => 'královská modr',
				'short sleeve'          => 'krátký rukáv',
				'lososová'              => 'lososová',
				'pruhledny'             => 'pruhledny',
				'pajamas'               => 'pyžama',
				'snowflake'             => 'sněhová vločka',
				'astronaut'             => 'astronaut',
				'dlsenjoy'              => 'dlsenjoy',
				'dlshei'                => 'dlshei',
				'fialova svetla'        => 'fialová světla',
				'pants'                 => 'kalhoty',
				'camellia red'          => 'kamélie červená',
				'lblue'                 => 'modrá',
				'nose screw'            => 'nosní šroub',
				'peony'                 => 'pivoňka',
				'straight pin'          => 'rovný čep',
				'eyelash unicorn pink'  => 'řasa jednorožec růžová',
				'triangle'              => 'trojúhelník',
				'cherry purple'         => 'třešňově fialová',
				'gd'                    => 'zlatá',
				'barevna'               => 'barevná',
				'tie dye'               => 'barva na kravatu',
				'blackbag black'        => 'černá',
				'hat'                   => 'čepice',
				'blackblue'             => 'černomodrá',
				'dgray'                 => 'šedá',
				'fluorescein'           => 'fluorescein',
				'ruzove'                => 'růžové',
				'světlé'                => 'světlý',
				'bag black'             => 'taška černá',
				'tmavé'                 => 'tmavé',
				'car'                   => 'auto',
				'balck'                 => 'balck',
				'long top pants'        => 'dlouhé svrchní kalhoty',
				'pumpkin'               => 'dýně',
				'silne narazuvzdorne'   => 'silne narazuvzdorne',
				'penguin'               => 'tučňák',
				'christmas red'         => 'vánoční červená',
				'blanco'                => 'blanco',
				'british flag'          => 'britská vlajka',
				'summer beige'          => 'letní béžová',
				'lotus color'           => 'lotosová barva',
				'medvídek'              => 'medvídek',
				'lightpink'             => 'světle růžová',
				'dress b'               => 'šaty b',
				'vinove'                => 'vínová',
				'apple green'           => 'zelené jablko',
				'winred'                => 'červená',
				'dlsbai'                => 'dlsbai',
				'geometry'              => 'geometrie',
				'pea green'             => 'hráškově zelená',
				'rough vertical bar'    => 'hrubá svislá lišta',
				'captain america'       => 'kapitán amerika',
				'leaves'                => 'listy',
				'meteor grey'           => 'meteor šedá',
				'monkey'                => 'opice',
				'stripes'               => 'pruhy',
				'rust red'              => 'rezavě červená',
				'lilac'                 => 'šeřík',
				'spain'                 => 'španělsko',
				'taro purple'           => 'taro fialová',
				'usb warm white'        => 'usb teplá bílá',
				'shown'                 => 'zobrazeno',
				'dgy'                   => 'šedá',
				'ee'                    => 'ee',
				'pant'                  => 'kalhoty',
				'chestnut'              => 'kaštan',
				'koala'                 => 'koala',
				'medvidci'              => 'medvidci',
				'mouse'                 => 'myš',
				'letters'               => 'písmena',
				'flat front white'      => 'ploché přední bílé',
				'rhododendron'          => 'rododendron',
				'fish'                  => 'ryba',
				'velvet brown'          => 'sametově hnědá',
				'laugh'                 => 'smát se',
				'ligth gray'            => 'světle šedá',
				'avocado'               => 'avokádo',
				'russet'                => 'červenohnědý',
				'dino'                  => 'dino',
				'grape purple'          => 'hroznově fialová',
				'mask'                  => 'maska',
				'meruňková'             => 'meruňková',
				'bat'                   => 'netopýr',
				'polarized'             => 'polarizované',
				'rosegold'              => 'rosegold',
				'chain'                 => 'řetěz',
				'thor'                  => 'thor',
				'transparentní'         => 'transparentní',
				'hulk'                  => 'vrak',
				'earth yellow'          => 'země žlutá',
				'shark'                 => 'žralok',
				'aa'                    => 'aqua modrá',
				'auto'                  => 'auto',
				'blackcamo'             => 'černá',
				'blackboots'            => 'černé boty',
				'kávová'                => 'kávová',
				'khakicamo'             => 'khaki',
				'king'                  => 'král',
				'leopardi'              => 'leopardi',
				'lev'                   => 'lev',
				'na'                    => 'na',
				'square'                => 'náměstí',
				'jade green'            => 'nefritově zelená',
				'ocean'                 => 'oceán',
				'plush black'           => 'plyšová černá',
				'kiss'                  => 'polibek',
				'cf'                    => 'srov',
				'greyorange'            => 'šedooranžová',
				'whale'                 => 'velryba',
				'greeen'                => 'zelená',
				'amry green'            => 'zelená',
				'quicksand case women'  => 'ženy pouzdro z tekutého písku',
				'bezove'                => 'béžová',
				'dlsjinbl'              => 'dlsjinbl',
				'duha'                  => 'duha',
				'duhová'                => 'duhová',
				'fialove'               => 'fialová',
				'round'                 => 'kolo',
				'crab'                  => 'krab',
				'kralicek'              => 'králíček',
				'turmeric'              => 'kurkuma',
				'kytky'                 => 'kytky',
				'lgy'                   => 'lgy',
				'newspaper'             => 'noviny',
				'olivová'               => 'olivová',
				'oranžové'              => 'oranžová',
				'pejsek'                => 'pejsek',
				'tree'                  => 'strom',
				'tmavá modrá'           => 'tmavá modrá',
				'military'              => 'válečný',
				'viz foto'              => 'viz foto',
				'wave point'            => 'vlnový bod',
				'whtie'                 => 'bílá',
				'žirafa'                => 'žirafa',
				'charcoal'              => 'dřevěné uhlí',
				'top'                   => 'horní',
				'jako obrazek'          => 'jako obrazek',
				'crystal transparent'   => 'krystal transparentní',
				'swan'                  => 'labuť',
				'small pink love'       => 'malá růžová láska',
				'sblue'                 => 'modrá',
				'mr'                    => 'pan',
				'pes'                   => 'pes',
				'full black'            => 'plná černá',
				'prouzky'               => 'prouzky',
				'purplish red'          => 'purpurově červená',
				'daisy'                 => 'sedmikráska',
				'skirt'                 => 'sukně',
				'sukne celenka'         => 'sukne celenka',
				'scarlet'               => 'šarlatový',
				'usmev'                 => 'úsměv',
				'female'                => 'ženský',
				'banana'                => 'banán',
				'barevné'               => 'barevné',
				'bla'                   => 'bla',
				'china'                 => 'čína',
				'hnědé'                 => 'hnědé',
				'starry sky'            => 'hvězdná obloha',
				'stars'                 => 'hvězdy',
				'cactus'                => 'kaktus',
				'cartoon'               => 'kreslená pohádka',
				'funny'                 => 'legrační',
				'original'              => 'originál',
				'champange'             => 'šampaňské',
				'pity'                  => 'škoda',
				'tmava modra'           => 'tmavá modrá',
				'tygr'                  => 'tygr',
				'bulbasaur'             => 'bulbasaur',
				'černobílá'             => 'černobílá',
				'rouge red'             => 'červená červená',
				'baby romper'           => 'dětské dudlík',
				'digital'               => 'digitální',
				'rainbowblack'          => 'duhově černá',
				'rainbowblue'           => 'duhově modrá',
				'rainbowpink'           => 'duhově růžová',
				'fotoaparat'            => 'fotoaparat',
				'capitan america'       => 'kapitán amerika',
				'kočka'                 => 'kočka',
				'fur black'             => 'kožešina černá',
				'ice blue'              => 'ledová modř',
				'shiny green'           => 'lesklá zelená',
				'mn black'              => 'mn černá',
				'carrot'                => 'mrkev',
				'parrot'                => 'papoušek',
				'spider'                => 'pavouk',
				'petticoat only'        => 'pouze spodnička',
				'natural white'         => 'přírodní bílá',
				'wheat blue'            => 'pšeničná modrá',
				'midnight blue'         => 'půlnoční modrá',
				'lips'                  => 'rty',
				'smiley'                => 'smajlík',
				'stegosaurus'           => 'stegosaurus',
				'greyblue'              => 'šedomodrá',
				'thin matt'             => 'tenký matný',
				'tepla bila'            => 'tepla bílá',
				'darkstar'              => 'tmavá hvězda',
				'three pictures'        => 'tři obrázky',
				'thickened light'       => 'zahuštěné světlo',
				'aqua blue'             => 'aqua modrá',
				'bilo cervena'          => 'bílo červená',
				'dolphin'               => 'delfín',
				'dk pink'               => 'dk růžová',
				'boys'                  => 'chlapci',
				'boy'                   => 'chlapec',
				'carmine'               => 'karmín',
				'maska'                 => 'maska',
				'moonlight'             => 'měsíční svit',
				'fog blue'              => 'mlhově modrá',
				'blu'                   => 'modrá',
				'opice'                 => 'opice',
				'pearl pink'            => 'perleťově růžová',
				'gradient planet'       => 'planeta s přechodem',
				'princeboy'             => 'princboy',
				'princessgirl'          => 'princezna',
				'plant'                 => 'rostlina',
				'celadon'               => 'seladon',
				'sunflower'             => 'slunečnice',
				'medium gray'           => 'středně šedá',
				'happy'                 => 'šťastný',
				'vintage'               => 'vintage',
				'waterproof'            => 'voděodolný',
				'amaranth'              => 'amarant',
				'asphalt'               => 'asfalt',
				'swhite'                => 'bílá',
				'azure bold striped'    => 'blankytně tučně pruhované',
				'bronzová'              => 'bronzová',
				'broskvova'             => 'broskvová',
				'cranberry'             => 'brusinka',
				'slate'                 => 'břidlice',
				'good camouflage'       => 'dobrá kamufláž',
				'drak blue'             => 'drak modrá',
				'fluorescence yellow'   => 'fluorescenční žlutá',
				'husky'                 => 'chraplavý',
				'ink green'             => 'inkoustově zelená',
				'lakerblue'             => 'jezerní modrá',
				'cowboy blue'           => 'kovbojská modrá',
				'lenochod'              => 'lenochod',
				'boat'                  => 'loď',
				'maskacova'             => 'maskáčová',
				'bluegrey'              => 'modrošedá',
				'stainless steel'       => 'nerezová ocel',
				'dandelion'             => 'pampeliška',
				'blank'                 => 'prázdný',
				'bird'                  => 'pták',
				'cute'                  => 'roztomilý',
				'angry'                 => 'rozzlobený',
				'pinkblue'              => 'růžovomodrá',
				'ms'                    => 'slečna',
				'smetanová'             => 'smetanová',
				'sred'                  => 'sred',
				'squirtle'              => 'veverka',
				'lightgreen'            => 'světle zelená',
				'světlehnědé'           => 'světlehnědé',
				'charmander'            => 'šarmander',
				'sgray'                 => 'šedivý',
				'thick black'           => 'tlustá černá',
				'wind red'              => 'vítr červený',
				'water is blue'         => 'voda je modrá',
				'embroidered'           => 'vyšívané',
				'sgreen'                => 'zelený',
				'winter jasmine'        => 'zimní jasmín',
				'aries'                 => 'beran',
				'bílo modrá'            => 'bílo modrá',
				'blak'                  => 'černá',
				'gemini'                => 'blíženci',
				'taurus'                => 'býk',
				'blackgray'             => 'černošedá',
				'blackgrey'             => 'černošedý',
				'wood'                  => 'dřevo',
				'football'              => 'fotbal',
				'coconut tree'          => 'kokosový strom',
				'capricorn'             => 'kozoroh',
				'lace black'            => 'krajka černá',
				'kralovsky modra'       => 'královský modrá',
				'flowers'               => 'květiny',
				'lava stone'            => 'lávový kámen',
				'leo'                   => 'lev',
				'matná stříbrná'        => 'matná stříbrná',
				'bluegreen'             => 'modrá zelená',
				'male'                  => 'mužský',
				'necklace'              => 'náhrdelník',
				'repair the moon'       => 'opravit měsíc',
				'virgo'                 => 'panna',
				'pepa'                  => 'pepa',
				'petrolejova'           => 'petrolejová',
				'prasatko'              => 'prasátko',
				'cancer'                => 'rakovina',
				'robot'                 => 'robot',
				'pisces'                => 'ryby',
				'dusk'                  => 'soumrak',
				'footprint'             => 'stopa',
				'sagittarius'           => 'střelec',
				'surfing'               => 'surfování',
				'symphony blue'         => 'symfonická modrá',
				'graypink'              => 'šedorůžová',
				'shorts'                => 'šortky',
				'spike picture a'       => 'špice obrázek a',
				'scorpio'               => 'štír',
				'libra'                 => 'váhy',
				'multicolour'           => 'vícebarevný',
				'aquarius'              => 'vodnář',
				'zarive ruzova'         => 'zářivě růžová',
				'england flag'          => 'anglická vlajka',
				'balloon'               => 'balón',
				'barevny'               => 'barevny',
				'beida'                 => 'beida',
				'whiteblack'            => 'bílo černá',
				'blackblackdyinwencai'  => 'černá',
				'blackblackdyinwenhon'  => 'černá',
				'blankytne modra'       => 'blankytně modrá',
				'blueblackdyinwencai'   => 'modro černá',
				'boluo'                 => 'boluo',
				'blackstripe'           => 'černý pruh',
				'diamond pink'          => 'diamantově růžová',
				'dragon'                => 'drak',
				'jungle camo'           => 'džungle camo',
				'pride edition'         => 'edice hrdosti',
				'beanred'               => 'fazolový',
				'fushia'                => 'fushia',
				'thunder'               => 'hrom',
				'starrysky'             => 'hvězdná obloha',
				'maple leaf'            => 'javorový list',
				'kahki'                 => 'kahki',
				'waterdrop'             => 'kapka vody',
				'cardigans'             => 'kardigany',
				'crimson'               => 'karmínový',
				'sweater khaki'         => 'khaki svetr',
				'kočička'               => 'kočička',
				'coconuttree'           => 'kokosový strom',
				'koralova'              => 'koralová',
				'lime green'            => 'limetkově zelená',
				'listy'                 => 'listy',
				'maths'                 => 'matematika',
				'meloun'                => 'meloun',
				'melounove'             => 'melounové',
				'fashion black'         => 'módní černá',
				'teal'                  => 'modrozelená',
				'motylci'               => 'motylci',
				'marbling'              => 'mramorování',
				'at the picture'        => 'na obrázku',
				'he'                    => 'on',
				'handprint'             => 'otisk ruky',
				'ovce'                  => 'ovce',
				'ovoce'                 => 'ovoce',
				'wig'                   => 'paruka',
				'feather'               => 'pírko',
				'sailboatrainbow'       => 'plachetnice',
				'platinum'              => 'platina',
				'desert camo'           => 'pouštní kamufláž',
				'superficial'           => 'povrchní',
				'pruhledna'             => 'pruhledna',
				'ruins green'           => 'ruiny zelené',
				'trees'                 => 'stromy',
				'lightpurple'           => 'světle fialová',
				'linght blue'           => 'světle modrá',
				'starlight'             => 'světlo hvězd',
				'pullover'              => 'svetr',
				'greystripe'            => 'šedý pruh',
				'vertical peony'        => 'vertikální pivoňka',
				'vin rouge'             => 'vin rouge',
				'walnut'                => 'vlašský ořech',
				'wolf'                  => 'vlk',
				'sunset'                => 'západ slunce',
				'eclipse'               => 'zatmění',
				'animal paradise'       => 'zvířecí ráj',
				'whitecotton'           => 'bílá bavlna',
				'blueboots'             => 'blueboots',
				'boho'                  => 'boho',
				'goden autumn'          => 'boží podzim',
				'bublinky'              => 'bublinky',
				'celo cerna'            => 'celá černá',
				'blackandwhite'         => 'černý a bílý',
				'cerveno zlate'         => 'červené zlaté',
				'four seasons'          => 'čtyři období',
				'remote and touch'      => 'dálkové a dotykové',
				'dkgreen'               => 'dkgreen',
				'dolores'               => 'dolores',
				'fds'                   => 'fds',
				'purpleboots'           => 'fialové boty',
				'fleece black blue'     => 'fleecová černo modrá',
				'grapefruit pink'       => 'grapefruitově růžová',
				'sponge'                => 'houba na mytí',
				'fine vertical stripe'  => 'jemný svislý pruh',
				'kakki'                 => 'haki',
				'keychain'              => 'klíčenka',
				'scyther'               => 'kosa',
				'skeleton'              => 'kostra',
				'horse'                 => 'kůň',
				'kytara'                => 'kytara',
				'modre noty'            => 'modre noty',
				'modro bílá'            => 'modro bílá',
				'modrý'                 => 'modrý',
				'powder blue'           => 'modrý prášek',
				'lattice'               => 'mříž',
				'nostalgic'             => 'nostalgický',
				'noty'                  => 'noty',
				'ohniva kytara'         => 'ohnivá kytara',
				'ohnivy klic'           => 'ohnivý klíč',
				'charming blue'         => 'okouzlující modrá',
				'pastelově duhová'      => 'pastelově duhová',
				'perspective'           => 'perspektivní',
				'plamenak'              => 'plamenák',
				'snakeskin print'       => 'potisk hadí kůže',
				'prase'                 => 'prase',
				'breathable'            => 'prodyšný',
				'powdery purple'        => 'pudrově fialová',
				'pinkcotton'            => 'růžová bavlna',
				'růžovo fialová'        => 'růžovo fialová',
				'samotna'               => 'samotna',
				'ze zipem'              => 'se zipem',
				'thousand love'         => 'tisíc lásky',
				'cloth'                 => 'tkanina',
				'tnave modra'           => 'tmavě modrá',
				'bigred'                => 'velká červená',
				'bigredboots'           => 'velké červené boty',
				'heather mavue'         => 'vřes mavue',
				'dream blue flower'     => 'vysněný modrý květ',
				'wert'                  => 'wert',
				'zeleno žlutá'          => 'zelená žlutá',
				'tortoise'              => 'želva',
				'amethyst'              => 'ametyst',
				'apply green'           => 'aplikovat zelenou',
				'berry color'           => 'barva bobule',
				'batika'                => 'batika',
				'whitegray'             => 'bílošedá',
				'blueblackdyinwenhon'   => 'modro černá',
				'bgreen'                => 'zelená',
				'blackstars'            => 'černé hvězdy',
				'blackthin'             => 'černá',
				'demon'                 => 'démon',
				'cattle'                => 'dobytek',
				'scrub blue'            => 'drhnout modře',
				'sequin black'          => 'flitr černý',
				'holograficke'          => 'holografické',
				'toydoll'               => 'hračka',
				'chrome color'          => 'chromová barva',
				'jednorozec'            => 'jednorozec',
				'kahaki'                => 'khaki',
				'kaki'                  => 'khaki',
				'classic black'         => 'klasická černá',
				'contrast flowers'      => 'kontrastní květiny',
				'kitty'                 => 'koťátko',
				'crocodile'             => 'krokodýl',
				'labut'                 => 'labuť',
				'lmw'                   => 'lmw',
				'lol'                   => 'lol',
				'little red flower'     => 'malý červený květ',
				'shallow lotus ash'     => 'mělký lotosový popel',
				'starfish'              => 'mořská hvězdice',
				'man'                   => 'muž',
				'mauve'                 => 'nafialovělý',
				'námořnická'            => 'námořnická',
				'od'                    => 'od',
				'five color flower'     => 'pětibarevný květ',
				'disdain'               => 'pohrdání',
				'minions'               => 'přisluhovači',
				'polka dot'             => 'puntíkovaný',
				'rice white'            => 'rýže bílá',
				'leash'                 => 'řemínek',
				'ruffle sleeve set'     => 'sada volánových rukávů',
				'sedy'                  => 'sedy',
				'slon'                  => 'slon',
				'sad'                   => 'smutný',
				'sleep'                 => 'spát',
				'sports black'          => 'sportovní černá',
				'middle blue'           => 'střední modrá',
				'studena bila'          => 'studena bila',
				'ribbon black'          => 'stuha černá',
				'tibetan green'         => 'tibetská zelená',
				'printing'              => 'tisk',
				'darkyellow'            => 'tmavě žlutá',
				'tigger'                => 'tygr',
				'tyrtysova'             => 'tyrtysova',
				'vegetable'             => 'zelenina',
				'turtle'                => 'želva',
				'zena'                  => 'žena',
				'colored star unicorn'  => 'barevný hvězdný jednorožec',
				'bckurky'               => 'bckurky',
				'belle dress'           => 'belle šaty',
				'bez kozisku cerne'     => 'bez kožíšku',
				'beigepearl'            => 'béžová perla',
				'beigeflower'           => 'béžový květ',
				'awhite'                => 'bílá',
				'bkleop'                => 'bkleop',
				'apale green'           => 'bledě zelená',
				'brazil'                => 'brazílie',
				'buldocek'              => 'buldoček',
				'blackcolor'            => 'černá barva',
				'blackpearl'            => 'černá perla',
				'blackpurple'           => 'černofialová',
				'blackflower'           => 'černokvět',
				'redboots'              => 'červené boty',
				'redbrown black'        => 'červenohnědá černá',
				'devil'                 => 'ďábel',
				'dinosauri'             => 'dinosauri',
				'erduo gray'            => 'šedá',
				'violets'               => 'fialová',
				'french'                => 'francouzština',
				'brownboots'            => 'hnědé boty',
				'brownsandals'          => 'hnědé sandály',
				'hvezda'                => 'hvězda',
				'his queen'             => 'jeho královna',
				'kalhoty'               => 'kalhoty',
				'khakiboots'            => 'khaki',
				'khakie'                => 'khaki',
				'donut'                 => 'kobliha',
				'shrimp'                => 'krevety',
				'led pant'              => 'led kalhoty',
				'maskáčová'             => 'maskáčová',
				'changeable'            => 'měnitelný',
				'apricote'              => 'meruňková',
				'anavy blue'            => 'modrá',
				'bluish purple'         => 'modrofialová',
				'bluepurple'            => 'modrofialová',
				'naked pink woman'      => 'nahá růžová žena',
				'navywhite'             => 'námořnická bílá',
				'asky blue'             => 'nebesky modrá',
				'ombre'                 => 'ombre',
				'opicka'                => 'opička',
				'sheep'                 => 'ovce',
				'paq'                   => 'paq',
				'blackno belt'          => 'pásek blackno',
				'cloak'                 => 'plášť',
				'police blue'           => 'policejní modrá',
				'strip c'               => 'proužek c',
				'pruple'                => 'pruple',
				'rosa'                  => 'rosa',
				'roseleop'              => 'roseleop',
				'rosepink'              => 'růžová růže',
				'roseblack'             => 'růžově černá',
				'sipky'                 => 'sipky',
				'sun flower'            => 'slunečnice',
				'old gold'              => 'staré zlato',
				'scarecrow'             => 'strašák',
				'styleb gray'           => 'styleb šedá',
				'stylec khaki'          => 'stylec khaki',
				'alight pink'           => 'světle růžové',
				'safflower'             => 'světlice barvířská',
				'lgrey'                 => 'šedá',
				'lgray'                 => 'šedá',
				'greyboots'             => 'šedé boty',
				'sneakers black red'    => 'tenisky černo červené',
				'darkgreyblack'         => 'tmavě šedočerná',
				'navyyellow'            => 'tmavě žlutá',
				'tmavohnědá'            => 'tmavohnědá',
				'dragonfly blue'        => 'vážka modrá',
				'winesandals'           => 'vinné sandály',
				'awine red'             => 'vínově červená',
				'vojenská zelená'       => 'vojenská zelená',
				'arose'                 => 'vznikl',
				'flag pattern i'        => 'vzor vlajky i',
				'greensandals'          => 'zelené sandály',
				'yelllow'               => 'žlutá',
				'yellowpearl'           => 'žlutá perla',
				'yellowish brown'       => 'žlutohnědá',
				'yellowflower'          => 'žlutý květ',
				'angel'                 => 'anděl',
				'armg green'            => 'armg zelená',
				'colorblue black'       => 'barva modrá černá',
				'picturecolor'          => 'barva obrázku',
				'batikovane cerne'      => 'batikovane cerne',
				'bezova khaki'          => 'béžová khaki',
				'blacke'                => 'černá',
				'blcak'                 => 'černá',
				'blonde pink'           => 'blond růžová',
				'bodysuits nude pink'   => 'body nahá růžová',
				'bodysuit light green'  => 'body světle zelená',
				'blueberry'             => 'borůvka',
				'britska lebka'         => 'britská lebka',
				'brontosaurus'          => 'brontosaurus',
				'bugs bunny'            => 'bugs bunny',
				'cai blcak'             => 'cai blcak',
				'tea'                   => 'čaj',
				'line'                  => 'čára',
				'witch'                 => 'čarodějnice',
				'černo bílá'            => 'černo bílá',
				'reddish brown'         => 'červenohnědá',
				'kids green model'      => 'dětský zelený model',
				'diasaur'               => 'diasaur',
				'dinosaurs'             => 'dinosauři',
				'fialkové'              => 'fialková',
				'fialovo sediva'        => 'fialovo sediva',
				'hd'                    => 'hd',
				'castle'                => 'hrad',
				'peagreen'              => 'hráškově zelená',
				'hvezdicky'             => 'hvězdičky',
				'nany'                  => 'chůva',
				'imitation platinum'    => 'imitace platiny',
				'indigo'                => 'indigo',
				'spring green'          => 'jarní zelená',
				'jasmine'               => 'jasmín',
				'laker blue'            => 'jezerní modrá',
				'lakeblue'              => 'jezerní modrá',
				'stone'                 => 'kámen',
				'sequined khaki'        => 'khaki s flitry',
				'khakipink'             => 'khaki',
				'coyot'                 => 'kojot',
				'hummingbird'           => 'kolibřík',
				'crown'                 => 'koruna',
				'guitar'                => 'kytara',
				'glacier blue'          => 'ledovcová modrá',
				'lined green'           => 'lemované zeleně',
				'glossy black leather'  => 'lesklá černá kůže',
				'los'                   => 'los',
				'maskacove zelene'      => 'maskáčové zeleně',
				'maskáčovégreen'        => 'maskáčovézelené',
				'maskakove cerna'       => 'maskákové černá',
				'kaji bear'             => 'medvěd kaji',
				'pricot'                => 'meruňka',
				'appricot'              => 'meruňka',
				'bluewhite'             => 'modrá bílá',
				'molv se'               => 'molv se',
				'mtee white'            => 'mtee bílá',
				'beatiful bedding'      => 'nádherné povlečení',
				'sailorblue white'      => 'námořník modrá bílá',
				'sailor blue black'     => 'námořník modrá černá',
				'nano tape'             => 'nano páska',
				'birthday lips'         => 'narozeninové rty',
				'non waterproof'        => 'ne voděodolný',
				'germany'               => 'německo',
				'neonova ruzova'        => 'neonová růže',
				'neonově žlutá'         => 'neonově žlutá',
				'suit light blue'       => 'oblek světle modrý',
				'olivegreen'            => 'olivově zelená',
				'orangeshort'           => 'oranžové krátké',
				'ornage grey'           => 'oranžově šedá',
				'eagle'                 => 'orel',
				'slippers blue'         => 'pantofle modré',
				'slipper gray'          => 'pantofle šedá',
				'pirate'                => 'pirát',
				'pistachio'             => 'pistácie',
				'plus velvet black'     => 'plus sametově černá',
				'cameo'                 => 'portrét',
				'tomato'                => 'rajče',
				'ruzovy'                => 'růžová',
				'sunglasses'            => 'sluneční brýle',
				'dimmable with remote'  => 'stmívatelné dálkovým ovládáním',
				'svetla zelena'         => 'světla zelená',
				'světlehnědá'           => 'světlehnědá',
				'champage'              => 'šampaňské',
				'scarf bear'            => 'šátek medvěd',
				'greyred'               => 'šedě',
				'greyblack'             => 'šedočerná',
				'dots'                  => 'tečky',
				'tshirt'                => 'tričko',
				'coffer'                => 'truhla',
				'ufo'                   => 'ufo',
				'greysnake'             => 'užovka popelavá',
				'velryba'               => 'velryba',
				'back'                  => 'zadní',
				'amy green'             => 'zelená',
				'zicron stone black'    => 'zicron kámen černý',
				'zlaty'                 => 'zlatá',
				'zviratka'              => 'zviratka',
				'animals'               => 'zvířata',
				'svitive zelena'        => 'živá zelená',
				'zlta'                  => 'žlutá',
				'yollew'                => 'žlutá',
				'watercolor green'      => 'akvarel zelená',
				'cars'                  => 'auta',
				'basketball'            => 'basketball',
				'whitegold clear'       => 'bílé zlato čiré',
				'whiteblue'             => 'bílomodrá',
				'blacka'                => 'černá',
				'blackaa'               => 'černá',
				'blackasiansize'        => 'černá',
				'pine green'            => 'borovice zelená',
				'cihlova'               => 'cihlová',
				'stranger things'       => 'cizí věci',
				'candy purple'          => 'cukroví fialová',
				'blackgold purple'      => 'černozlatá fialová',
				'chinese deep blue'     => 'čínská tmavě modrá',
				'dinosaurus'            => 'dinosaurus',
				'adult black green'     => 'dospělý černozelený',
				'ecru'                  => 'ecru',
				'bikini purple'         => 'fialové bikiny',
				'octopus'               => 'chobotnice',
				'jachta'                => 'jachta',
				'jarní černá'           => 'jarní černá',
				'singel panty'          => 'jednotné kalhotky',
				'her king'              => 'její král',
				'crotchless panties'    => 'kalhotky bez rozkroku',
				'canada'                => 'kanada',
				'khat stripes'          => 'khat pruhy',
				'khika'                 => 'khika',
				'kozoroh'               => 'kozoroh',
				'royel blue b'          => 'královská modř b',
				'chick'                 => 'kuřátko',
				'plane'                 => 'letadlo',
				'letadlo'               => 'letadlo',
				'airplane'              => 'letoun',
				'lavanda'               => 'levandule',
				'ginkgo leaf'           => 'list ginkgo',
				'liška'                 => 'liška',
				'mintgreen'             => 'mátově zelená',
				'winnie'                => 'medvídek',
				'moonstone'             => 'měsíční kámen',
				'flour cow'             => 'moučná kráva',
				'wall mounted'          => 'na stěnu',
				'neonove zluta'         => 'neonově žlutá',
				'netopyr'               => 'netopýr',
				'low cut black'         => 'nízký střih černé',
				'eyes'                  => 'oči',
				'orangegrey'            => 'oranžově šedá',
				'island style'          => 'ostrovním stylu',
				'open crotch panties'   => 'otevřené kalhotky v rozkroku',
				'palm purple'           => 'palmově fialová',
				'sandy waterproof'      => 'písčitá voděodolná',
				'underwater world'      => 'podvodní svět',
				'autumn black'          => 'podzimní černá',
				'fairy powder'          => 'pohádkový prášek',
				'pokemon hoodie'        => 'pokemon mikina s kapucí',
				'positioning flower'    => 'polohovací květina',
				'popelka'               => 'popelka',
				'cinderella'            => 'popelka',
				'prasátko'              => 'prasátko',
				'powdered strawberry'   => 'prášková jahoda',
				'princess pink'         => 'princezna růžová',
				'stripy girl'           => 'pruhovaná dívka',
				'auspicious red'        => 'příznivá červená',
				'publue'                => 'publue',
				'puntiky'               => 'puntiky',
				'rocket'                => 'raketa',
				'raketa'                => 'raketa',
				'russia'                => 'rusko',
				'gardenia rose'         => 'růže gardénie',
				'pinkpurple'            => 'růžovofialová',
				'ryba'                  => 'ryba',
				'toys set'              => 'sada hraček',
				'sedo ruzove'           => 'sedo růžové',
				'net red finger'        => 'síťový červený prst',
				'glass green'           => 'sklo zelené',
				'skublue'               => 'skublue',
				'slonici'               => 'slonici',
				'slonova kost'          => 'slonova kost',
				'ladybug'               => 'slunéčko sedmitečné',
				'sunny yellow'          => 'slunečně žlutá',
				'snehurka'              => 'sněhurka',
				'ancient silver'        => 'starověké stříbro',
				'national flag'         => 'státní vlajka',
				'velcro black'          => 'suchý zip černý',
				'super'                 => 'super',
				'brightyellow'          => 'světle žlutá',
				'bandanna'              => 'šátek',
				'deepgray'              => 'tmavě šedá',
				'tractor'               => 'traktor',
				'tricerotops'           => 'trierotops',
				'tricko'                => 'trik',
				'tropical leaves'       => 'tropické listy',
				'grade camouflage'      => 'třídní kamufláž',
				'tučňák'                => 'tučňák',
				'bee'                   => 'včela',
				'vegeta'                => 'vegeta',
				'large'                 => 'velký',
				'velryby'               => 'velryby',
				'publack'               => 'veřejnost',
				'vesmir'                => 'vesmír',
				'vinona'                => 'vinona',
				'left'                  => 'vlevo, odjet',
				'vlk'                   => 'vlk',
				'withe'                 => 'vrbový prut',
				'sob'                   => 'vzlyk',
				'whitec'                => 'bílá',
				'whiteh'                => 'bílá',
				'whitei'                => 'bílá',
				'recessed in'           => 'zapuštěný v',
				'brightblue'            => 'zářivě modrá',
				'zimní černá'           => 'zimní černá',
				'heightened bla'        => 'zvýšené bla',
				'none picture'          => 'žádný obrázek',
				'right'                 => 'že jo',
				'tortoiseshell'         => 'želvovina',
				'yellowgold'            => 'žluté zlato',
				'cardigan and scarf'    => 'cardigan a šátek',
				'duch s rouskou'        => 'duch s rouskou',
				'eu plug charger'       => 'eu nabíječka',
				'jasper black h'        => 'jaspis černý h',
				'pocket with zipper'    => 'kapsa se zipem',
				'wings of freedom'      => 'křídla svobody',
				'mango yellow cotton'   => 'mangově žlutá bavlna',
				'harry potter hoodie'   => 'mikina s kapucí harry potter',
				'crayon shin chan'      => 'pastelka shin chan',
				'sede alien hi'         => 'sede mimozemšťan ahoj',
				'singlenet white pink'  => 'singlenet bílá růžová',
				'singlnet white green'  => 'singlenet bílá zelená',
				'hooded light pink'     => 'světle růžová s kapucí',
				'teambride light blue'  => 'teambride světle modrá',
				'app remote control'    => 'dálkové ovládání aplikace',
				'greeb usb charging'    => 'USB dobíjení',
				'dense forest green'    => 'hustá lesní zeleň',
				'lovely girl cotton'    => 'krásná holčičí bavlna',
				'laser rose gold'       => 'laserové růžové zlato',
				'macaron sky blue'      => 'macaron nebesky modrá',
				'maka blue mesh'        => 'maka modrá síťovina',
				'calf length butterf'   => 'motýl délky po lýtka',
				'froest gray green'     => 'mráz šedozelená',
				'turtleneck wine red'   => 'rolák vínově červený',
				'amongus clothes set'   => 'sada oblečení',
				'tankini set green'     => 'sada tankini zelená',
				'sandals white blue'    => 'sandály bílo modré',
				'standing old man'      => 'stojící starý muž',
				'stylea deep brown'     => 'stylea tmavě hnědá',
				'lilght rose gold'      => 'světle růžové zlato',
				'styled rose red'       => 've stylu růžově červené',
				'flip flops beige'      => 'žabky béžové',
				'gz black set'          => 'černá sada gz',
				'puff sleeve bk'        => 'nafouknutý rukáv bk',
				'sent at random'        => 'odesláno náhodně',
				'armpit should pad'     => 'podpaží by mělo vycpávat',
				'strong dog leash'      => 'silné psí vodítko',
				'imp on horseback'      => 'skřítek na koni',
				'vzor plody moře'       => 'vzor plody moře',
				'glow in dark'          => 'zářit ve tmě',
				'yeellow and blue'      => 'žluté a modré',
				'lady blue grid'        => 'dáma modrá mřížka',
				'creative wave marble'  => 'kreativní vlnový mramor',
				'shiiny rose gold'      => 'lesklé růžové zlato',
				'hight waist blue'      => 'modrý vysoký pas',
				'fluffy coffee bear'    => 'nadýchaný kávový medvěd',
				'nighty lake blue'      => 'noční jezerní modrá',
				'sunscreen thin blue'   => 'opalovací krém tenký modrý',
				'fra bra black'         => 'podprsenka černá',
				'handsome one love'     => 'pohledná láska',
				'rope add crown'        => 'provaz přidat korunu',
				'robe lake blue'        => 'roucho jezerní modré',
				'rutilated quartz sedy' => 'rutilovaný křemen sedy',
				'solar blue light'      => 'solární modré světlo',
				'filling pp cotton'     => 'výplň pp bavlna',
				'bibs mint green'       => 'bryndáčky mátově zelené',
				'whole black leather'   => 'celá černá kůže',
				'leaher silver green'   => 'kožená stříbrná zelená',
				'gloss black wood'      => 'lesklé černé dřevo',
				'plain socks red'       => 'obyčejné ponožky červené',
				'fruite green a'        => 'ovocná zelená a',
				'swimming ring a'       => 'plavecký kroužek a',
				'shoulder carrier b'    => 'ramenní nosič b',
				'rock cyan black'       => 'rock azurově černá',
				'ruby red heart'        => 'rubínově červené srdce',
				'nail polish thinner'   => 'ředidlo laku na nehty',
				'skype blue wood'       => 'skype modré dřevo',
				'arrow silver black'    => 'šipka stříbrná černá',
				'valentine girl boy'    => 'valentine dívka chlapec',
				'close eye panda'       => 'zavřít oko panda'
			);
			if ( $translate[ $color ] ) {
				return $translate[ $color ];
			} else {
				return $color;
			}
		}

		public function size_translate( $size ) {
			$sizes = [
				"3m"       => "3 měsíce",
				"6m"       => "6 měsíců",
				"9m"       => "9 měsíců",
				"12m"      => "12 měsíců",
				"18m"      => "18 měsíců",
				"24m"      => "24 měsíců",
				"2t"       => "2 roky",
				"3t"       => "3 roky",
				"4t"       => "4 roky",
				"5t"       => "5 roky",
				"6t"       => "6 let",
				"7t"       => "7 let",
				"8t"       => "8 let",
				"9t"       => "9 let",
				"10t"      => "10 let",
				"11t"      => "11 let",
				"12t"      => "12 let",
				"13t"      => "13 let",
				"14t"      => "14 let",
				"15t"      => "15 let",
				"one-size" => "univerzální velikost",
				"uni"      => "univerzální velikost",
				"iphone"   => "iPhone",
			];

			if ( $sizes[ $size ] ) {
				return $sizes[ $size ];
			} else {
				return $size;
			}
		}

		public function remove_strings( $string ) {

			$to_remove = array( 'china', 'for' );


			foreach ( $to_remove as $word ) {
				$string = str_replace( $word, '', $string );
			}

			return $string;
		}

		public function possible_attributes_sizes() {
			return implode( '|', array(
				'siz',
				'veliko',
				'size',
				'pa_axis-body',
				'pa_ballon-size',
				'pa_bands-size',
				'pa_electra-velikost',
				'pa_gift-bag-size',
				'pa_gift-box-size',
				'pa_gloves-size',
				'pa_hat-size',
				'pa_christmas-hat-size',
				'pa_kid-size',
				'pa_kid-us-size',
				'pa_king-velikost',
				'pa_luggage-size',
				'pa_plate-size',
				'pa_product-size',
				'pa_ring-size',
				'pa_sheet-size',
				'pa_shoe-size',
				'pa_size',
				'pa_size-inch',
				'pa_size-shape-style',
				'pa_sizecm',
				'pa_snowflake-size',
				'pa_sticker-size',
				'pa_the-king-velikost',
				'pa_the-queen-velikost',
				'pa_tweeter-size',
				'pa_tweeter-size-set-type',
				'pa_us-size',
				'pa_veikost',
				'pa_vel',
				'pa_veleikost',
				'pa_velikoist',
				'pa_velikos',
				'pa_velikosat',
				'pa_velikosst',
				'pa_velikost',
				'pa_velikost-barva',
				'pa_velikost-boty',
				'pa_velikost-cm',
				'pa_velikost-detsky',
				'pa_velikost-eur',
				'pa_velikost-kosicku',
				'pa_velikost-l',
				'pa_velikost-l-44',
				'pa_velikost-m-41',
				'pa_velikost-s',
				'pa_velikost-s-38',
				'pa_velikost-satu',
				'pa_velikost-serie',
				'pa_velikost-us',
				'pa_velikost-xl',
				'pa_velikost-xl-46',
				'pa_velikost-xs-35',
				'pa_velikost12',
				'pa_velikost2',
				'pa_velikostcm',
				'pa_velikosti',
				'pa_velikostt',
				'pa_velikosz',
				'pa_velikoti',
				'pa_veliksot',
				'pa_veliskost',
				'pa_velka',
				'pa_velkost',
				'pa_velky',
				'pa_vellikost',
				'pa_veloikost',
				'pa_vvelikost',
				'pa_woofer-size-full-rang',
				'bands-size',
				'cup-size',
				'child-size',
				'kid-size',
				'maternity-size',
				'pet-size',
				'pick-size',
				'ring-size',
				'sheet-size',
				'shoe-size',
				'size',
				'size-inch',
				'sizecm',
				'pa_detska-velikost',
				'pa_cup-size',
				'pa_ballon-size',
				'pa_bands-size',
				'pa_belt-length',
				'child-size',
				'delka',
				'kid-size',
				'pa_gloves-size',
				'pa_kid-size',
				'pa_luggage-size',
				'pa_maternity-size',
				'pa_pick-size',
				'pa_plate-size',
				'pa_product-size',
				'pa_ring-size',
				'pa_sheet-size',
				'pa_shoe-size',
				'pa_size',
				'pa_size-inch',
				'pa_sizecm',
				'pa_specification',
				'pa_sticker-size',
				'pa_stretched-length',
				'pa_the-king-velikost',
				'pa_the-king-velkost',
				'pa_the-queen-velikost',
				'pa_the-queen-velkost',
				'pa_us-size',
				'pa_velikosat',
				'pa_velikost',
				'pa_velikost-pasma',
				'pa_velikost-pasu',
				'pa_velikost-prstenu',
				'pa_velikosti',
				'pa_velikostsize',
				'pa_veliksot',
				'pa_velkost',
				'pa_velkost-nohy',
				'pa_velkost-podpatku',
				'pa_velkost-postavy',
				'pa_vellikost',
				'pa_veloikost',
				'pa_vvelikost',
				'ring-size',
				'shoe-size',
				'size',
				'size-inch',
				'velikost',
				'velkost',
				'pa_velikost-kosicku',
				'pa_cup-size',
				'pa_velikost-obvodu',
				'pa_velikost-podpatku',
				'veli'
			) );
		}

		public function possible_attributes_color() {
			return implode( '|', array(
				'barv',
				'farb',
				'pa_band-color',
				'pa_barvy',
				'pa_bava',
				'pa_bavra',
				'pa_body-color',
				'pa_brava',
				'pa_color',
				'pa_color-frame',
				'pa_color-name',
				'pa_color-temperature',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_f',
				'pa_farba',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_metal-color',
				'band-color',
				'barva',
				'barva-led',
				'barva-osvetleni',
				'body-color',
				'color',
				'color-name',
				'emitting-color',
				'frame-color',
				'gem-color',
				'handle-color',
				'lampshade-color',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'barva',
				'color',
				'color-name',
				'body-color',
				'emitting-color',
				'farba',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'pa_barav',
				'pa_barava',
				'pa_barva',
				'pa_barva-bryli',
				'pa_barva-cocek',
				'pa_barva-cocky',
				'pa_barva-led',
				'pa_barva-obroucek',
				'pa_barva-ramu',
				'pa_barva-sklicek',
				'pa_barva-stetcu',
				'pa_barva-varianta',
				'pa_barvy',
				'pa_bavra',
				'pa_bila',
				'pa_bila-s-motivy',
				'pa_body-color',
				'pa_brava',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_material',
				'pa_metal-color',
				'pa_color-name',
				'pa_color',
				'pa_color-frame',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_farba',
				'pa_farba-a-velkost',
				'pa_farba-podsvietenia',
				'pa_farby',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'band-color',
				'barva-led',
				'body-color',
				'color-name',
				'color',
				'emitting-color',
				'frame-color',
				'gem-color',
				'handle-color',
				'lampshade-color',
				'lenses-color',
				'main-stone-color',
				'metal-color',
				'pa_band-color',
				'pa_bava',
				'pa_bavra',
				'pa_body-color',
				'pa_brava',
				'pa_color-frame',
				'pa_color-name',
				'pa_color-temperature',
				'pa_color',
				'pa_colors',
				'pa_colour',
				'pa_cor',
				'pa_couleur',
				'pa_emitting-color',
				'pa_f',
				'pa_farba',
				'pa_frame-color',
				'pa_gem-color',
				'pa_handle-color',
				'pa_lampshade-color',
				'pa_lenses-color',
				'pa_metal-color',
				'barva',
				'farba',
				'pa_barav',
				'pa_barava',
				'pa_barva-varianta',
				'pa_barva',
				'pa_barvy',
				'pa_bila-s-motivy',
				'pa_bila',
				'pa_farba-a-velkost',
				'pa_farba-podsvietenia',
				'pa_farby',
				'pa_size-emitting-color',
				'colo'
			) );
		}

	}
}
